# bootstrap_project.py
# Generated by CircuIT — do not edit manually
#
# PURPOSE : Creates all source files for pyats-kpi-calculator
# USAGE   : ~/.bootstrap-venv/bin/python bootstrap_project.py
# NOTE    : Run from inside pyats-kpi-calculator/ directory

from ai_bootstrap import Bootstrap


# ===============================================================
# FILE CONTENTS
# ===============================================================

PYPROJECT_TOML = """
[tool.poetry]
name        = "pyats-kpi-calculator"
version     = "0.1.8"
description = "PyATS Offline KPI Calculator — Extract KPIs from captured NX-OS/IOS-XE/IOS-XR show command outputs"
readme      = "README.md"
packages    = [{include = "kpi_calculator.py"}]
keywords    = [
    "cisco",
    "pyats",
    "genie",
    "network-automation",
    "nxos",
    "iosxe",
    "iosxr",
    "kpi",
    "network-monitoring"
]

[tool.poetry.dependencies]
python              = ">=3.10,<4.0"
pyats               = ">=23.0"
genie               = ">=23.0"
"genie.libs.parser" = ">=23.0"
PyYAML              = ">=6.0"
schema              = ">=0.7.5"

[tool.poetry.group.dev.dependencies]
pytest        = ">=7.4"
pytest-cov    = ">=4.1"
ruff          = ">=0.1.0"
mypy          = ">=1.5"
types-PyYAML  = ">=6.0"

[tool.poetry.scripts]
kpi-calculator = "kpi_calculator:main"

[build-system]
requires      = ["poetry-core>=1.7.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
verbosity = 2
addopts   = "--cov=kpi_calculator --cov-report=term-missing"

[tool.ruff]
line-length    = 79
target-version = "py310"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "UP"]
ignore = ["E501"]

[tool.mypy]
python_version         = "3.10"
warn_return_any        = true
warn_unused_configs    = true
ignore_missing_imports = true
"""


KPI_CALCULATOR_PY = """
# kpi_calculator.py
# Generated by CircuIT — do not edit manually

import os
import sys
import json
import argparse
import importlib
from datetime import datetime

import yaml
from schema import Schema, And, Or, Optional, SchemaError
from genie.conf.base import Device


# ---------------------------------------------------------------
# Constants
# ---------------------------------------------------------------

VALID_OPERATIONS  = ["sum", "count", "max", "min", "avg", "sum_lengths"]
SUPPORTED_OS      = ["nxos", "iosxe", "iosxr"]
KPI_MODELS_FILE   = "kpi_models.yaml"
DEFAULT_INPUT_DIR = "input_files"
DEFAULT_VERBOSITY = 2

# Verbosity levels
VERBOSITY_SILENT  = 0   # No console output
VERBOSITY_MINIMAL = 1   # One line per KPI: name + value
VERBOSITY_NORMAL  = 2   # Condensed — show/file/status/value
VERBOSITY_VERBOSE = 3   # Full — all fields + breakdown

# Genie parser parameter names to try in order
# output= works with NX-OS parsers in current Genie version
# text= is tried as fallback for other versions
PARSE_PARAMS = ["output", "text"]


# ---------------------------------------------------------------
# Supported Operations Registry
# ---------------------------------------------------------------

OPERATIONS = {
    "sum":         lambda values: sum(values),
    "count":       lambda values: len(values),
    "max":         lambda values: max(values) if values else 0,
    "min":         lambda values: min(values) if values else 0,
    "avg":         lambda values: sum(values) / len(values) if values else 0,
    "sum_lengths": lambda values: sum(len(v) if isinstance(v, dict) else v
                                      for v in values)
}


# ---------------------------------------------------------------
# Schema Definitions
# ---------------------------------------------------------------

OS_SOURCE_SCHEMA = Schema({
    "show_command":  And(str, len,
                        error="show_command must be a non-empty string"),
    "parser_module": And(str, len,
                        error="parser_module must be a non-empty string"),
    "parser_class":  And(str, len,
                        error="parser_class must be a non-empty string")
})

FILTER_SCHEMA = Schema({
    "key":   And(str, len, error="filter.key must be a non-empty string"),
    "value": And(str, len, error="filter.value must be a non-empty string")
})

KPI_ENTRY_SCHEMA = Schema({
    "description": And(
        str, len,
        error="description must be a non-empty string"
    ),
    "source": And(
        dict,
        lambda s: len(s) > 0,
        lambda s: all(os_key in SUPPORTED_OS for os_key in s.keys()),
        lambda s: all(OS_SOURCE_SCHEMA.is_valid(v) for v in s.values()),
        error=(
            f"source must define at least one supported OS "
            f"{SUPPORTED_OS} with show_command, "
            f"parser_module and parser_class"
        )
    ),
    "iterate": Or(
        And(str, len),
        And(
            list,
            lambda l: len(l) > 0,
            lambda l: all(isinstance(i, str) and len(i) > 0 for i in l)
        ),
        error="iterate must be a non-empty string or list of strings"
    ),
    Optional("value_key"): And(
        str, len,
        error="value_key must be a non-empty string"
    ),
    "operation": And(
        str,
        lambda op: op in VALID_OPERATIONS,
        error=f"operation must be one of: {VALID_OPERATIONS}"
    ),
    Optional("filter"): And(
        dict,
        lambda f: FILTER_SCHEMA.is_valid(f),
        error="filter must have non-empty 'key' and 'value' fields"
    ),
    "default": And(
        int,
        lambda n: n >= 0,
        error="default must be a non-negative integer"
    )
})

KPI_MODELS_SCHEMA = Schema({
    And(str, len): KPI_ENTRY_SCHEMA
})


# ---------------------------------------------------------------
# CLI Argument Parser
# ---------------------------------------------------------------

def parse_arguments() -> argparse.Namespace:
    \"\"\"
    Parses CLI arguments.

    Usage:
      python kpi_calculator.py --router <name> --os <os_type>
                               [--kpis KPI1 KPI2 ...]
                               [--input-dir <dir>]
                               [--models <file>]
                               [--list-kpis]
                               [--verbosity 0|1|2|3]
                               [--output-json <file>]

    Verbosity levels:
      0 = silent  -- no console output
      1 = minimal -- one line per KPI: name + value
      2 = normal  -- condensed output (default)
      3 = verbose -- full output with breakdown

    Examples:
      # Normal output (default)
      python kpi_calculator.py --router n7k --os nxos

      # Minimal one-line output
      python kpi_calculator.py --router n7k --os nxos
          --verbosity 1

      # Silent with JSON output only
      python kpi_calculator.py --router n7k --os nxos
          --verbosity 0
          --output-json results.json

      # Full verbose output + JSON
      python kpi_calculator.py --router n7k --os nxos
          --verbosity 3
          --output-json results.json
    \"\"\"
    parser = argparse.ArgumentParser(
        description="PyATS Offline KPI Calculator",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--router",
        required=True,
        help="Router name used to derive input file names."
    )
    parser.add_argument(
        "--os",
        required=True,
        choices=SUPPORTED_OS,
        help=f"Network OS type. Supported: {SUPPORTED_OS}"
    )
    parser.add_argument(
        "--models",
        default=KPI_MODELS_FILE,
        help=f"Path to KPI models YAML file. "
             f"Default: {KPI_MODELS_FILE}"
    )
    parser.add_argument(
        "--input-dir",
        default=DEFAULT_INPUT_DIR,
        dest="input_dir",
        help=f"Directory containing show command output files. "
             f"Default: {DEFAULT_INPUT_DIR}"
    )
    parser.add_argument(
        "--kpis",
        nargs="+",
        default=None,
        metavar="KPI_NAME",
        help=(
            "Space-separated list of KPI names to calculate. "
            "If not specified all KPIs are calculated. "
            "Example: --kpis total_routes total_vrfs"
        )
    )
    parser.add_argument(
        "--list-kpis",
        action="store_true",
        default=False,
        dest="list_kpis",
        help="List all available KPI names and exit."
    )
    parser.add_argument(
        "--verbosity",
        type=int,
        choices=[0, 1, 2, 3],
        default=DEFAULT_VERBOSITY,
        metavar="LEVEL",
        help=(
            "Console output verbosity level. "
            "0=silent 1=minimal 2=normal (default) 3=verbose"
        )
    )
    parser.add_argument(
        "--output-json",
        default=None,
        dest="output_json",
        metavar="FILE",
        help=(
            "Write KPI results to JSON file. "
            "Example: --output-json results.json"
        )
    )
    return parser.parse_args()


# ---------------------------------------------------------------
# YAML Model Loader + Validator
# ---------------------------------------------------------------

def validate_kpi_models(models: dict) -> bool:
    \"\"\"
    Validates all KPI model entries individually.
    Returns True if all models are valid, False otherwise.
    \"\"\"
    all_valid = True
    for kpi_name, kpi_entry in models.items():
        try:
            KPI_ENTRY_SCHEMA.validate(kpi_entry)
        except SchemaError as e:
            print(f"  [FAIL] KPI '{kpi_name}': {e}")
            all_valid = False
    return all_valid


def load_kpi_models(filepath: str) -> dict:
    \"\"\"
    Loads KPI model definitions from YAML file and validates
    the complete structure.
    \"\"\"
    try:
        with open(filepath, "r") as f:
            models = yaml.safe_load(f)
        if not isinstance(models, dict):
            print(f"[ERROR] KPI models file must contain "
                  f"a YAML dictionary at the top level.")
            sys.exit(1)
    except FileNotFoundError:
        print(f"[ERROR] KPI models file not found: '{filepath}'")
        sys.exit(1)
    except yaml.YAMLError as e:
        print(f"[ERROR] Failed to parse YAML file: {e}")
        sys.exit(1)

    print(f"[INFO] Validating KPI models from '{filepath}' ...")
    try:
        KPI_MODELS_SCHEMA.validate(models)
    except SchemaError as e:
        print(f"[ERROR] Top-level schema validation failed: {e}")
        sys.exit(1)

    print(f"[INFO] Validating {len(models)} KPI entries ...")
    if not validate_kpi_models(models):
        print(f"\\n[ERROR] One or more KPI models failed validation.")
        sys.exit(1)

    print(f"[INFO] Schema validation passed — "
          f"{len(models)} KPI models loaded.\\n")
    return models


# ---------------------------------------------------------------
# KPI Selection
# ---------------------------------------------------------------

def select_kpis(kpi_models: dict,
                requested:  list | None) -> dict:
    \"\"\"
    Filters KPI models to only the requested KPIs.
    If requested is None returns all KPIs unchanged.
    \"\"\"
    if requested is None:
        return kpi_models

    available     = set(kpi_models.keys())
    requested_set = set(requested)
    not_found     = requested_set - available

    if not_found:
        print(f"\\n[ERROR] Unknown KPI name(s): "
              f"{sorted(not_found)}")
        print(f"\\n  Available KPIs in '{KPI_MODELS_FILE}':")
        for name in sorted(available):
            desc = kpi_models[name].get("description", "")
            print(f"    {name:<30} -- {desc}")
        print()
        sys.exit(1)

    return {
        name: model
        for name, model in kpi_models.items()
        if name in requested_set
    }


def list_kpis(kpi_models: dict) -> None:
    \"\"\"
    Prints all available KPI names and descriptions then exits.
    \"\"\"
    print(f"\\n  Available KPIs ({len(kpi_models)} total):\\n")
    print(f"  {'KPI Name':<35} Description")
    print(f"  {'-' * 35} {'-' * 40}")
    for name, model in kpi_models.items():
        desc = model.get("description", "")
        print(f"  {name:<35} {desc}")
    print()


# ---------------------------------------------------------------
# Dynamic Parser Class Resolver
# ---------------------------------------------------------------

def resolve_parser_class(parser_module: str, parser_class: str):
    \"\"\"
    Dynamically imports and returns a parser class.
    \"\"\"
    try:
        module = importlib.import_module(parser_module)
        return getattr(module, parser_class)
    except ModuleNotFoundError:
        print(f"[ERROR] Parser module not found: '{parser_module}'")
        sys.exit(1)
    except AttributeError:
        print(f"[ERROR] Parser class '{parser_class}' not found "
              f"in module '{parser_module}'")
        sys.exit(1)


# ---------------------------------------------------------------
# File Name Derivation
# ---------------------------------------------------------------

def derive_filename(router_name: str,
                    show_command: str,
                    input_dir: str = DEFAULT_INPUT_DIR,
                    extension: str = "txt") -> str:
    \"\"\"
    Derives full input file path from router name,
    show command and input directory.

    Convention:
      <input_dir>/<router_name>__<show_command_underscored>.<ext>

    Examples:
      router="n7k", cmd="show ip route summary"
        -> "input_files/n7k__show_ip_route_summary.txt"
    \"\"\"
    command_part = show_command.lower().replace(" ", "_")
    filename     = f"{router_name}__{command_part}.{extension}"
    return os.path.join(input_dir, filename)


# ---------------------------------------------------------------
# Multi-Level Iterator
# ---------------------------------------------------------------

def collect_leaf_items(data: dict, keys: list) -> list:
    \"\"\"
    Recursively traverses nested dicts using a list of keys,
    collecting all leaf-level item dictionaries.
    \"\"\"
    if not keys:
        if isinstance(data, dict):
            return list(data.values())
        return []
    current_key = keys[0]
    remaining   = keys[1:]
    section     = data.get(current_key, {})
    leaf_items  = []
    for item_data in section.values():
        leaf_items.extend(collect_leaf_items(item_data, remaining))
    return leaf_items


# ---------------------------------------------------------------
# Dot-Notation Path Resolver
# ---------------------------------------------------------------

def resolve_path(data: dict, path: str) -> dict:
    \"\"\"
    Resolves a dot-notation string path into a nested dictionary.
    \"\"\"
    for key in path.split("."):
        if isinstance(data, dict):
            data = data.get(key, {})
        else:
            return {}
    return data


# ---------------------------------------------------------------
# Device Factory
# ---------------------------------------------------------------

def create_device(router_name: str, os_type: str) -> Device:
    device = Device(router_name, os=os_type)
    device.custom.setdefault("abstraction", {})["order"] = ["os"]
    return device


# ---------------------------------------------------------------
# File Reader
# ---------------------------------------------------------------

def read_input_file(filepath: str) -> str:
    \"\"\"
    Reads raw CLI output from file.
    Tries multiple encodings to handle files captured
    from different platforms and tools.
    \"\"\"
    encodings = ["utf-8", "cp1252", "latin-1"]

    for encoding in encodings:
        try:
            with open(filepath, "r", encoding=encoding) as f:
                content = f.read()
            if encoding != "utf-8":
                print(f"[INFO] File '{filepath}' read "
                      f"using encoding: {encoding}")
            return content
        except UnicodeDecodeError:
            continue
        except FileNotFoundError:
            print(f"[ERROR] File not found: '{filepath}'")
            print(f"        Expected convention: "
                  f"<input_dir>/<router>__<show_command>.txt")
            print(f"        Check --input-dir argument "
                  f"(default: {DEFAULT_INPUT_DIR})")
            sys.exit(1)
        except IOError as e:
            print(f"[ERROR] Could not read file '{filepath}': {e}")
            sys.exit(1)

    print(f"[ERROR] Could not decode '{filepath}' "
          f"with any supported encoding: {encodings}")
    sys.exit(1)


# ---------------------------------------------------------------
# Genie Parser -- Try Multiple Parameter Names
# ---------------------------------------------------------------

def _try_parse(parser_class,
               device,
               raw_output: str,
               show_command: str) -> dict:
    \"\"\"
    Attempts offline parsing trying parameter names in the
    order defined by PARSE_PARAMS constant.
    \"\"\"
    parser = parser_class(device=device)
    errors = []

    for param_name in PARSE_PARAMS:
        try:
            result = parser.parse(**{param_name: raw_output})
            return result
        except TypeError as e:
            errors.append(f"{param_name}= : {e}")
            continue
        except Exception as e:
            print(f"[ERROR] Parsing failed for '{show_command}': {e}")
            print(f"        Parser  : {parser_class.__name__}")
            print(f"        Param   : {param_name}=")
            sys.exit(1)

    print(f"[ERROR] Could not find working parse parameter "
          f"for '{show_command}'")
    print(f"        Parser : {parser_class.__name__}")
    print(f"        Tried  : {PARSE_PARAMS}")
    for err in errors:
        print(f"        {err}")
    sys.exit(1)


# ---------------------------------------------------------------
# Model-Driven Parser
# ---------------------------------------------------------------

def parse_output(model: dict,
                 router_name: str,
                 os_type: str,
                 input_dir: str,
                 parse_cache: dict,
                 verbosity: int) -> dict | None:
    \"\"\"
    Selects OS-specific show_command and parser_class from
    the YAML model, dynamically resolves the parser class,
    and performs offline parsing.
    Uses parse cache to avoid re-parsing the same file.
    \"\"\"
    source    = model.get("source", {})
    os_source = source.get(os_type)

    if not os_source:
        return None

    show_command  = os_source.get("show_command")
    parser_module = os_source.get("parser_module")
    parser_class  = os_source.get("parser_class")

    if not all([show_command, parser_module, parser_class]):
        print(f"[ERROR] Incomplete source entry for OS '{os_type}'.")
        sys.exit(1)

    input_file = derive_filename(router_name, show_command, input_dir)

    if input_file in parse_cache:
        if verbosity >= VERBOSITY_VERBOSE:
            print(f"[CACHE] Using cached result for: '{input_file}'")
        return parse_cache[input_file]

    if verbosity >= VERBOSITY_VERBOSE:
        print(f"[INFO] Router    : '{router_name}'")
        print(f"[INFO] OS        : '{os_type}'")
        print(f"[INFO] Command   : '{show_command}'")
        print(f"[INFO] Input dir : '{input_dir}'")
        print(f"[INFO] File      : '{input_file}'")

    resolved_class = resolve_parser_class(parser_module, parser_class)
    device         = create_device(router_name, os_type)
    raw_output     = read_input_file(input_file)

    parsed = _try_parse(
        resolved_class, device, raw_output, show_command
    )
    parse_cache[input_file] = parsed
    return parsed


# ---------------------------------------------------------------
# Generic KPI Calculator
# ---------------------------------------------------------------

def calculate_kpi(model: dict, parsed_output: dict) -> dict:
    \"\"\"
    Generic KPI calculator supporting single-level and
    multi-level iteration with optional value filtering.
    \"\"\"
    iterate    = model.get("iterate")
    value_key  = model.get("value_key")
    operation  = model.get("operation", "sum")
    default    = model.get("default", 0)
    filter_def = model.get("filter")

    if operation not in OPERATIONS:
        return {
            "status":  "error",
            "message": f"Unsupported operation: '{operation}'. "
                       f"Supported: {VALID_OPERATIONS}"
        }

    if isinstance(iterate, list):
        leaf_items = collect_leaf_items(parsed_output, iterate)

        if not leaf_items:
            return {
                "status":      "warning",
                "description": model.get("description"),
                "value":       default,
                "message":     f"No data found at path: {iterate}"
            }

        if filter_def:
            filter_key   = filter_def.get("key")
            filter_value = filter_def.get("value")
            leaf_items   = [
                item for item in leaf_items
                if item.get(filter_key) == filter_value
            ]

        collected_values   = (
            [item.get(value_key, default) for item in leaf_items]
            if value_key else leaf_items
        )
        result_value       = OPERATIONS[operation](collected_values)
        per_item_breakdown = {"matched_items": len(leaf_items)}

    else:
        iterable_section = resolve_path(parsed_output, iterate)

        if not iterable_section:
            return {
                "status":      "warning",
                "description": model.get("description"),
                "value":       default,
                "message":     f"No data found at path: '{iterate}'"
            }

        collected_values   = []
        per_item_breakdown = {}

        for item_name, item_data in iterable_section.items():
            value = item_data.get(value_key, default)
            collected_values.append(value)
            per_item_breakdown[item_name] = (
                len(value) if isinstance(value, dict) else value
            )

        result_value = OPERATIONS[operation](collected_values)

    return {
        "status":      "ok",
        "description": model.get("description"),
        "operation":   operation,
        "value":       result_value,
        "breakdown":   per_item_breakdown
    }


# ---------------------------------------------------------------
# Output Formatting
# ---------------------------------------------------------------

def print_kpi_result(kpi_name: str,
                     model: dict,
                     result: dict,
                     router_name: str,
                     os_type: str,
                     input_dir: str,
                     verbosity: int) -> None:
    \"\"\"
    Prints KPI result to console at requested verbosity level.

    Level 0 (silent)  : no output
    Level 1 (minimal) : one line — KPI name + value
    Level 2 (normal)  : condensed — command, file, status, value
    Level 3 (verbose) : full — all fields + breakdown
    \"\"\"
    if verbosity == VERBOSITY_SILENT:
        return

    os_source    = model.get("source", {}).get(os_type, {})
    show_command = os_source.get("show_command", "N/A")
    input_file   = derive_filename(router_name, show_command, input_dir)
    status       = result.get("status")
    value        = result.get("value")

    # --- Level 1: minimal ---
    if verbosity == VERBOSITY_MINIMAL:
        status_tag = "" if status == "ok" else f" [{status.upper()}]"
        print(f"  {kpi_name:<35} : {value}{status_tag}")
        return

    # --- Level 2: normal ---
    if verbosity == VERBOSITY_NORMAL:
        print(f"\\n  {'KPI':<18} : {kpi_name}")
        print(f"  {'Description':<18} : {result.get('description')}")
        print(f"  {'Show Command':<18} : {show_command}")
        print(f"  {'Input File':<18} : {input_file}")
        print(f"  {'Status':<18} : {status}")
        print(f"  {'Value':<18} : {value}")
        if status == "warning":
            print(f"  {'Message':<18} : {result.get('message')}")
        return

    # --- Level 3: verbose ---
    print("\\n" + "=" * 60)
    print(f"  KPI          : {kpi_name}")
    print("=" * 60)
    print(f"  Description  : {result.get('description')}")
    print(f"  Router       : {router_name}")
    print(f"  OS           : {os_type}")
    print(f"  Show Command : {show_command}")
    print(f"  Input Dir    : {input_dir}")
    print(f"  Input File   : {input_file}")
    print(f"  Status       : {status}")
    print(f"  Operation    : {result.get('operation')}")
    if model.get("filter"):
        f = model.get("filter")
        print(f"  Filter       : {f.get('key')} == '{f.get('value')}'")
    print(f"\\n  Breakdown:")
    for item, val in result.get("breakdown", {}).items():
        print(f"    {item:<25} : {val}")
    print(f"\\n  Result Value : {value}")
    print("=" * 60 + "\\n")


# ---------------------------------------------------------------
# JSON Output
# ---------------------------------------------------------------

def build_json_output(router_name: str,
                      os_type: str,
                      results: dict) -> dict:
    \"\"\"
    Builds the JSON output structure from collected results.

    Structure:
    {
        "router":    "<router_name>",
        "os":        "<os_type>",
        "timestamp": "<ISO 8601 timestamp>",
        "kpis": {
            "<kpi_name>": {
                "description": "<str>",
                "value":       <int|float>,
                "status":      "<str>",
                "operation":   "<str>"
            },
            ...
        }
    }
    \"\"\"
    return {
        "router":    router_name,
        "os":        os_type,
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "kpis": {
            kpi_name: {
                "description": result.get("description", ""),
                "value":       result.get("value"),
                "status":      result.get("status"),
                "operation":   result.get("operation")
            }
            for kpi_name, result in results.items()
        }
    }


def write_json_output(json_data: dict,
                      filepath: str,
                      verbosity: int) -> None:
    \"\"\"
    Writes JSON output to file.
    \"\"\"
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(json_data, f, indent=2)
        if verbosity > VERBOSITY_SILENT:
            print(f"\\n[INFO] JSON output written to: '{filepath}'")
    except IOError as e:
        print(f"[ERROR] Could not write JSON output "
              f"to '{filepath}': {e}")
        sys.exit(1)


# ---------------------------------------------------------------
# Main
# ---------------------------------------------------------------

def main():
    args        = parse_arguments()
    router_name = args.router
    os_type     = args.os
    models_file = args.models
    input_dir   = args.input_dir
    requested   = args.kpis
    verbosity   = args.verbosity
    output_json = args.output_json
    parse_cache = {}
    results     = {}

    # --- Load and validate all KPI models ---
    kpi_models = load_kpi_models(models_file)

    # --- Handle --list-kpis flag ---
    if args.list_kpis:
        list_kpis(kpi_models)
        sys.exit(0)

    # --- Filter to requested KPIs ---
    selected_models = select_kpis(kpi_models, requested)

    # --- Print header ---
    if verbosity >= VERBOSITY_NORMAL:
        print(f"\\n{'=' * 60}")
        print(f"  PyATS Offline KPI Calculator")
        print(f"  Router     : {router_name}")
        print(f"  OS         : {os_type}")
        print(f"  Models File: {models_file}")
        print(f"  Input Dir  : {input_dir}")
        print(f"  KPIs       : "
              f"{'all (' + str(len(selected_models)) + ')' if requested is None else str(requested)}")
        if output_json:
            print(f"  JSON Output: {output_json}")
        print(f"{'=' * 60}\\n")
    elif verbosity == VERBOSITY_MINIMAL:
        print(f"\\n  Router: {router_name}  OS: {os_type}\\n")

    # --- Validate input directory ---
    if not os.path.isdir(input_dir):
        print(f"[ERROR] Input directory not found: '{input_dir}'")
        sys.exit(1)

    # --- Calculate selected KPIs ---
    for kpi_name, model in selected_models.items():
        parsed_output = parse_output(
            model, router_name, os_type,
            input_dir, parse_cache, verbosity
        )
        if parsed_output is None:
            if verbosity >= VERBOSITY_NORMAL:
                print(f"[SKIP] KPI '{kpi_name}' -- "
                      f"OS '{os_type}' not supported.\\n")
            continue

        result = calculate_kpi(model, parsed_output)
        results[kpi_name] = result

        print_kpi_result(
            kpi_name, model, result,
            router_name, os_type, input_dir, verbosity
        )

    # --- Write JSON output if requested ---
    if output_json and results:
        json_data = build_json_output(router_name, os_type, results)
        write_json_output(json_data, output_json, verbosity)

    # --- Minimal footer ---
    if verbosity == VERBOSITY_MINIMAL:
        total  = len(results)
        ok     = sum(1 for r in results.values()
                     if r.get("status") == "ok")
        warn   = total - ok
        suffix = f"  ({warn} warnings)" if warn else ""
        print(f"\\n  Total: {total} KPIs calculated{suffix}\\n")


if __name__ == "__main__":
    main()
"""


KPI_MODELS_YAML = """
total_routes:
  description: "Total number of IP routes across all VRFs"
  source:
    nxos:
      show_command:  "show ip route summary"
      parser_module: "genie.libs.parser.nxos.show_routing"
      parser_class:  "ShowIpRouteSummary"
    iosxe:
      show_command:  "show ip route summary"
      parser_module: "genie.libs.parser.iosxe.show_routing"
      parser_class:  "ShowIpRouteSummary"
    iosxr:
      show_command:  "show route summary"
      parser_module: "genie.libs.parser.iosxr.show_routing"
      parser_class:  "ShowRouteSummary"
  iterate:   "vrf"
  value_key: "total_routes"
  operation: "sum"
  default:   0

max_routes_in_vrf:
  description: "Highest route count found in a single VRF"
  source:
    nxos:
      show_command:  "show ip route summary"
      parser_module: "genie.libs.parser.nxos.show_routing"
      parser_class:  "ShowIpRouteSummary"
    iosxe:
      show_command:  "show ip route summary"
      parser_module: "genie.libs.parser.iosxe.show_routing"
      parser_class:  "ShowIpRouteSummary"
    iosxr:
      show_command:  "show route summary"
      parser_module: "genie.libs.parser.iosxr.show_routing"
      parser_class:  "ShowRouteSummary"
  iterate:   "vrf"
  value_key: "total_routes"
  operation: "max"
  default:   0

total_vrfs:
  description: "Total number of VRFs with routing information"
  source:
    nxos:
      show_command:  "show ip route summary"
      parser_module: "genie.libs.parser.nxos.show_routing"
      parser_class:  "ShowIpRouteSummary"
    iosxe:
      show_command:  "show ip route summary"
      parser_module: "genie.libs.parser.iosxe.show_routing"
      parser_class:  "ShowIpRouteSummary"
    iosxr:
      show_command:  "show route summary"
      parser_module: "genie.libs.parser.iosxr.show_routing"
      parser_class:  "ShowRouteSummary"
  iterate:   "vrf"
  value_key: "total_routes"
  operation: "count"
  default:   0

total_mac_addresses:
  description: "Total number of MAC addresses across all VLANs"
  source:
    nxos:
      show_command:  "show mac address-table"
      parser_module: "genie.libs.parser.nxos.show_fdb"
      parser_class:  "ShowMacAddressTable"
    iosxe:
      show_command:  "show mac address-table"
      parser_module: "genie.libs.parser.iosxe.show_l2"
      parser_class:  "ShowMacAddressTable"
  iterate:   "mac_table.vlans"
  value_key: "mac_addresses"
  operation: "sum_lengths"
  default:   0

total_bgp_neighbors:
  description: "Total number of BGP neighbors across all VRFs"
  source:
    nxos:
      show_command:  "show bgp summary"
      parser_module: "genie.libs.parser.nxos.show_bgp"
      parser_class:  "ShowBgpSummary"
    iosxe:
      show_command:  "show bgp summary"
      parser_module: "genie.libs.parser.iosxe.show_bgp"
      parser_class:  "ShowBgpSummary"
    iosxr:
      show_command:  "show bgp summary"
      parser_module: "genie.libs.parser.iosxr.show_bgp"
      parser_class:  "ShowBgpSummary"
  iterate:
    - "vrf"
    - "neighbor"
  operation: "count"
  default:   0

total_bgp_routes_rib:
  description: "Total BGP prefixes received across all VRFs, neighbors and address families"
  source:
    nxos:
      show_command:  "show bgp all summary"
      parser_module: "genie.libs.parser.nxos.show_bgp"
      parser_class:  "ShowBgpAllSummary"
    iosxe:
      show_command:  "show bgp all summary"
      parser_module: "genie.libs.parser.iosxe.show_bgp"
      parser_class:  "ShowBgpAllSummary"
    iosxr:
      show_command:  "show bgp all all summary"
      parser_module: "genie.libs.parser.iosxr.show_bgp"
      parser_class:  "ShowBgpAllAllSummary"
  iterate:
    - "vrf"
    - "neighbor"
    - "address_family"
  value_key: "prefixes_received"
  operation: "sum"
  default:   0

total_bfd_sessions_up:
  description: "Total number of BFD sessions in Up state"
  source:
    nxos:
      show_command:  "show bfd neighbors"
      parser_module: "genie.libs.parser.nxos.show_bfd"
      parser_class:  "ShowBfdNeighbors"
    iosxe:
      show_command:  "show bfd neighbors"
      parser_module: "genie.libs.parser.iosxe.show_bfd"
      parser_class:  "ShowBfdNeighbors"
    iosxr:
      show_command:  "show bfd all-interfaces"
      parser_module: "genie.libs.parser.iosxr.show_bfd"
      parser_class:  "ShowBfdAllInterfaces"
  iterate:
    - "our_address"
    - "neighbor_address"
  operation: "count"
  filter:
    key:   "state"
    value: "Up"
  default:   0

total_bfd_sessions_down:
  description: "Total number of BFD sessions in Down state"
  source:
    nxos:
      show_command:  "show bfd neighbors"
      parser_module: "genie.libs.parser.nxos.show_bfd"
      parser_class:  "ShowBfdNeighbors"
    iosxe:
      show_command:  "show bfd neighbors"
      parser_module: "genie.libs.parser.iosxe.show_bfd"
      parser_class:  "ShowBfdNeighbors"
    iosxr:
      show_command:  "show bfd all-interfaces"
      parser_module: "genie.libs.parser.iosxr.show_bfd"
      parser_class:  "ShowBfdAllInterfaces"
  iterate:
    - "our_address"
    - "neighbor_address"
  operation: "count"
  filter:
    key:   "state"
    value: "Down"
  default:   0
"""


TEST_SCHEMA_PY = """
# tests/test_schema.py
# Generated by CircuIT -- do not edit manually

import pytest
from schema import SchemaError
from kpi_calculator import (
    KPI_MODELS_SCHEMA,
    KPI_ENTRY_SCHEMA,
    OS_SOURCE_SCHEMA,
    FILTER_SCHEMA,
    validate_kpi_models
)


def test_valid_os_source_passes():
    OS_SOURCE_SCHEMA.validate({
        "show_command":  "show ip route summary",
        "parser_module": "genie.libs.parser.nxos.show_routing",
        "parser_class":  "ShowIpRouteSummary"
    })


def test_os_source_missing_field_fails():
    with pytest.raises(SchemaError):
        OS_SOURCE_SCHEMA.validate({
            "show_command":  "show ip route summary",
            "parser_module": "genie.libs.parser.nxos.show_routing"
        })


def test_os_source_empty_string_fails():
    with pytest.raises(SchemaError):
        OS_SOURCE_SCHEMA.validate({
            "show_command":  "",
            "parser_module": "genie.libs.parser.nxos.show_routing",
            "parser_class":  "ShowIpRouteSummary"
        })


def test_valid_filter_passes():
    FILTER_SCHEMA.validate({"key": "state", "value": "Up"})


def test_filter_empty_value_fails():
    with pytest.raises(SchemaError):
        FILTER_SCHEMA.validate({"key": "state", "value": ""})


def test_filter_missing_key_fails():
    with pytest.raises(SchemaError):
        FILTER_SCHEMA.validate({"value": "Up"})


def test_valid_entry_passes():
    KPI_ENTRY_SCHEMA.validate({
        "description": "Total routes",
        "source": {
            "nxos": {
                "show_command":  "show ip route summary",
                "parser_module": "genie.libs.parser.nxos.show_routing",
                "parser_class":  "ShowIpRouteSummary"
            }
        },
        "iterate":   "vrf",
        "value_key": "total_routes",
        "operation": "sum",
        "default":   0
    })


def test_invalid_os_key_fails():
    with pytest.raises(SchemaError):
        KPI_ENTRY_SCHEMA.validate({
            "description": "Total routes",
            "source": {
                "invalid_os": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "sum",
            "default":   0
        })


def test_invalid_operation_fails():
    with pytest.raises(SchemaError):
        KPI_ENTRY_SCHEMA.validate({
            "description": "Total routes",
            "source": {
                "nxos": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "invalid_op",
            "default":   0
        })


def test_negative_default_fails():
    with pytest.raises(SchemaError):
        KPI_ENTRY_SCHEMA.validate({
            "description": "Total routes",
            "source": {
                "nxos": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "sum",
            "default":   -1
        })


def test_list_iterate_passes():
    KPI_ENTRY_SCHEMA.validate({
        "description": "BGP neighbors",
        "source": {
            "nxos": {
                "show_command":  "show bgp summary",
                "parser_module": "genie.libs.parser.nxos.show_bgp",
                "parser_class":  "ShowBgpSummary"
            }
        },
        "iterate":   ["vrf", "neighbor"],
        "operation": "count",
        "default":   0
    })


def test_empty_list_iterate_fails():
    with pytest.raises(SchemaError):
        KPI_ENTRY_SCHEMA.validate({
            "description": "BGP neighbors",
            "source": {
                "nxos": {
                    "show_command":  "show bgp summary",
                    "parser_module": "genie.libs.parser.nxos.show_bgp",
                    "parser_class":  "ShowBgpSummary"
                }
            },
            "iterate":   [],
            "operation": "count",
            "default":   0
        })


def test_empty_source_fails():
    with pytest.raises(SchemaError):
        KPI_ENTRY_SCHEMA.validate({
            "description": "Total routes",
            "source":      {},
            "iterate":     "vrf",
            "operation":   "sum",
            "default":     0
        })


def test_optional_value_key_absent_passes():
    KPI_ENTRY_SCHEMA.validate({
        "description": "BGP neighbors",
        "source": {
            "nxos": {
                "show_command":  "show bgp summary",
                "parser_module": "genie.libs.parser.nxos.show_bgp",
                "parser_class":  "ShowBgpSummary"
            }
        },
        "iterate":   ["vrf", "neighbor"],
        "operation": "count",
        "default":   0
    })


def test_validate_kpi_models_all_valid():
    models = {
        "kpi_one": {
            "description": "KPI one",
            "source": {
                "nxos": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "sum",
            "default":   0
        }
    }
    assert validate_kpi_models(models) is True


def test_validate_kpi_models_reports_all_failures():
    models = {
        "kpi_good": {
            "description": "Good KPI",
            "source": {
                "nxos": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "sum",
            "default":   0
        },
        "kpi_bad": {
            "description": "Bad KPI",
            "source": {
                "nxos": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "invalid_op",
            "default":   0
        }
    }
    assert validate_kpi_models(models) is False
"""


TEST_CALCULATOR_PY = """
# tests/test_calculator.py
# Generated by CircuIT -- do not edit manually

import pytest
import json
import os
from kpi_calculator import (
    calculate_kpi,
    collect_leaf_items,
    resolve_path,
    select_kpis,
    build_json_output,
    write_json_output,
    VERBOSITY_SILENT
)


def test_resolve_path_single_key():
    data   = {"vrf": {"default": {"total_routes": 100}}}
    result = resolve_path(data, "vrf")
    assert "default" in result


def test_resolve_path_dot_notation():
    data   = {"mac_table": {"vlans": {"10": {"mac_addresses": {}}}}}
    result = resolve_path(data, "mac_table.vlans")
    assert "10" in result


def test_resolve_path_missing_key():
    data   = {"vrf": {}}
    result = resolve_path(data, "vrf.missing")
    assert result == {}


def test_collect_leaf_items_single_level():
    data = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5}
        }
    }
    items = collect_leaf_items(data, ["vrf"])
    assert len(items) == 2


def test_collect_leaf_items_two_levels():
    data = {
        "vrf": {
            "default": {
                "neighbor": {
                    "1.1.1.1": {"state": "Established"},
                    "2.2.2.2": {"state": "Established"}
                }
            }
        }
    }
    items = collect_leaf_items(data, ["vrf", "neighbor"])
    assert len(items) == 2


def test_calculate_kpi_sum():
    model  = {
        "description": "Total routes",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "sum",
        "default":     0
    }
    parsed = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5}
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 105


def test_calculate_kpi_count():
    model  = {
        "description": "Total VRFs",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "count",
        "default":     0
    }
    parsed = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5},
            "prod":    {"total_routes": 200}
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 3


def test_calculate_kpi_max():
    model  = {
        "description": "Max routes",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "max",
        "default":     0
    }
    parsed = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5},
            "prod":    {"total_routes": 200}
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 200


def test_calculate_kpi_with_filter():
    model  = {
        "description": "BFD Up",
        "iterate":     ["our_address", "neighbor_address"],
        "operation":   "count",
        "filter":      {"key": "state", "value": "Up"},
        "default":     0
    }
    parsed = {
        "our_address": {
            "10.0.0.1": {
                "neighbor_address": {
                    "10.0.0.2": {"state": "Up"},
                    "10.0.0.3": {"state": "Down"},
                    "10.0.0.4": {"state": "Up"}
                }
            }
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 2


def test_calculate_kpi_invalid_operation():
    model  = {
        "description": "Test",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "invalid",
        "default":     0
    }
    parsed = {"vrf": {"default": {"total_routes": 100}}}
    result = calculate_kpi(model, parsed)
    assert result["status"] == "error"


def test_calculate_kpi_empty_data():
    model  = {
        "description": "Test",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "sum",
        "default":     0
    }
    parsed = {"vrf": {}}
    result = calculate_kpi(model, parsed)
    assert result["status"] == "warning"
    assert result["value"]  == 0


SAMPLE_MODELS = {
    "total_routes": {
        "description": "Total routes",
        "source": {
            "nxos": {
                "show_command":  "show ip route summary",
                "parser_module": "genie.libs.parser.nxos.show_routing",
                "parser_class":  "ShowIpRouteSummary"
            }
        },
        "iterate":   "vrf",
        "value_key": "total_routes",
        "operation": "sum",
        "default":   0
    },
    "total_vrfs": {
        "description": "Total VRFs",
        "source": {
            "nxos": {
                "show_command":  "show ip route summary",
                "parser_module": "genie.libs.parser.nxos.show_routing",
                "parser_class":  "ShowIpRouteSummary"
            }
        },
        "iterate":   "vrf",
        "value_key": "total_routes",
        "operation": "count",
        "default":   0
    },
    "max_routes_in_vrf": {
        "description": "Max routes in VRF",
        "source": {
            "nxos": {
                "show_command":  "show ip route summary",
                "parser_module": "genie.libs.parser.nxos.show_routing",
                "parser_class":  "ShowIpRouteSummary"
            }
        },
        "iterate":   "vrf",
        "value_key": "total_routes",
        "operation": "max",
        "default":   0
    }
}


def test_select_kpis_none_returns_all():
    result = select_kpis(SAMPLE_MODELS, None)
    assert result == SAMPLE_MODELS


def test_select_kpis_single():
    result = select_kpis(SAMPLE_MODELS, ["total_routes"])
    assert list(result.keys()) == ["total_routes"]


def test_select_kpis_multiple():
    result = select_kpis(
        SAMPLE_MODELS, ["total_routes", "total_vrfs"]
    )
    assert set(result.keys()) == {"total_routes", "total_vrfs"}


def test_select_kpis_preserves_order():
    result = select_kpis(
        SAMPLE_MODELS,
        ["max_routes_in_vrf", "total_routes"]
    )
    assert list(result.keys()) == [
        "total_routes", "max_routes_in_vrf"
    ]


def test_select_kpis_unknown_exits():
    with pytest.raises(SystemExit):
        select_kpis(SAMPLE_MODELS, ["nonexistent_kpi"])


def test_select_kpis_partial_unknown_exits():
    with pytest.raises(SystemExit):
        select_kpis(
            SAMPLE_MODELS,
            ["total_routes", "nonexistent_kpi"]
        )


# ---------------------------------------------------------------
# JSON output tests
# ---------------------------------------------------------------

SAMPLE_RESULTS = {
    "total_routes": {
        "description": "Total routes",
        "value":       47,
        "status":      "ok",
        "operation":   "sum"
    },
    "total_vrfs": {
        "description": "Total VRFs",
        "value":       1,
        "status":      "ok",
        "operation":   "count"
    }
}


def test_build_json_output_structure():
    data = build_json_output("n7k", "nxos", SAMPLE_RESULTS)
    assert data["router"]    == "n7k"
    assert data["os"]        == "nxos"
    assert "timestamp"       in data
    assert "kpis"            in data
    assert "total_routes"    in data["kpis"]
    assert "total_vrfs"      in data["kpis"]


def test_build_json_output_kpi_fields():
    data = build_json_output("n7k", "nxos", SAMPLE_RESULTS)
    kpi  = data["kpis"]["total_routes"]
    assert kpi["value"]     == 47
    assert kpi["status"]    == "ok"
    assert kpi["operation"] == "sum"
    assert "description"    in kpi


def test_build_json_output_timestamp_format():
    data = build_json_output("n7k", "nxos", SAMPLE_RESULTS)
    from datetime import datetime
    datetime.fromisoformat(data["timestamp"])


def test_write_json_output_creates_file(tmp_path):
    filepath = str(tmp_path / "output.json")
    data     = build_json_output("n7k", "nxos", SAMPLE_RESULTS)
    write_json_output(data, filepath, VERBOSITY_SILENT)
    assert os.path.exists(filepath)


def test_write_json_output_valid_json(tmp_path):
    filepath = str(tmp_path / "output.json")
    data     = build_json_output("n7k", "nxos", SAMPLE_RESULTS)
    write_json_output(data, filepath, VERBOSITY_SILENT)
    with open(filepath) as f:
        loaded = json.load(f)
    assert loaded["router"] == "n7k"
    assert loaded["os"]     == "nxos"
    assert len(loaded["kpis"]) == 2


def test_write_json_output_correct_values(tmp_path):
    filepath = str(tmp_path / "output.json")
    data     = build_json_output("n7k", "nxos", SAMPLE_RESULTS)
    write_json_output(data, filepath, VERBOSITY_SILENT)
    with open(filepath) as f:
        loaded = json.load(f)
    assert loaded["kpis"]["total_routes"]["value"] == 47
    assert loaded["kpis"]["total_vrfs"]["value"]   == 1
"""


TEST_PARSER_PY = """
# tests/test_parser.py
# Generated by CircuIT -- do not edit manually

import pytest
from unittest.mock import MagicMock
from kpi_calculator import (
    derive_filename,
    resolve_parser_class,
    _try_parse,
    PARSE_PARAMS
)


def test_derive_filename_basic():
    result = derive_filename("n7k", "show ip route summary")
    assert result == "input_files/n7k__show_ip_route_summary.txt"


def test_derive_filename_custom_input_dir():
    result = derive_filename(
        "n7k", "show ip route summary",
        input_dir="/data/captures"
    )
    assert result == \
        "/data/captures/n7k__show_ip_route_summary.txt"


def test_derive_filename_with_hyphen():
    result = derive_filename("n7k", "show mac address-table")
    assert result == \
        "input_files/n7k__show_mac_address-table.txt"


def test_derive_filename_iosxr_command():
    result = derive_filename("asr9k", "show route summary")
    assert result == \
        "input_files/asr9k__show_route_summary.txt"


def test_derive_filename_iosxe_router():
    result = derive_filename("cat9k", "show ip route summary")
    assert result == \
        "input_files/cat9k__show_ip_route_summary.txt"


def test_derive_filename_custom_extension():
    result = derive_filename(
        "n7k", "show ip route summary",
        extension="log"
    )
    assert result == "input_files/n7k__show_ip_route_summary.log"


def test_resolve_valid_parser_class():
    cls = resolve_parser_class(
        "genie.libs.parser.nxos.show_routing",
        "ShowIpRouteSummary"
    )
    assert cls is not None


def test_resolve_correct_mac_parser():
    cls = resolve_parser_class(
        "genie.libs.parser.nxos.show_fdb",
        "ShowMacAddressTable"
    )
    assert cls is not None


def test_resolve_invalid_module():
    with pytest.raises(SystemExit):
        resolve_parser_class(
            "genie.libs.parser.nxos.nonexistent_module",
            "ShowIpRouteSummary"
        )


def test_resolve_invalid_class():
    with pytest.raises(SystemExit):
        resolve_parser_class(
            "genie.libs.parser.nxos.show_routing",
            "NonExistentClass"
        )


def test_parse_params_order():
    assert PARSE_PARAMS[0] == "output"
    assert PARSE_PARAMS[1] == "text"


def test_try_parse_uses_output_param():
    mock_device          = MagicMock()
    mock_result          = {"vrf": {"default": {"total_routes": 47}}}
    mock_parser_instance = MagicMock()
    mock_parser_instance.parse.return_value = mock_result
    mock_parser_class    = MagicMock(return_value=mock_parser_instance)

    result = _try_parse(
        mock_parser_class,
        mock_device,
        "raw output text",
        "show ip route summary"
    )

    assert result == mock_result
    mock_parser_instance.parse.assert_called_once_with(
        output="raw output text"
    )


def test_try_parse_falls_back_to_text_param():
    mock_device          = MagicMock()
    mock_result          = {"vrf": {"default": {"total_routes": 47}}}
    mock_parser_instance = MagicMock()
    mock_parser_instance.parse.side_effect = [
        TypeError("unexpected keyword argument 'output'"),
        mock_result
    ]
    mock_parser_class = MagicMock(return_value=mock_parser_instance)

    result = _try_parse(
        mock_parser_class,
        mock_device,
        "raw output text",
        "show ip route summary"
    )

    assert result == mock_result
    assert mock_parser_instance.parse.call_count == 2
"""


README_MD = (
    "# pyats-kpi-calculator\n"
    "\n"
    "PyATS Offline KPI Calculator -- Extract KPIs from captured\n"
    "NX-OS, IOS-XE and IOS-XR show command outputs.\n"
    "\n"
    "## Installation\n"
    "\n"
    "```bash\n"
    "poetry install\n"
    "```\n"
    "\n"
    "## Usage\n"
    "\n"
    "```bash\n"
    "# Run all KPIs (normal output)\n"
    "poetry run kpi-calculator --router n7k --os nxos\n"
    "\n"
    "# Minimal one-line output\n"
    "poetry run kpi-calculator --router n7k --os nxos \\\n"
    "                          --verbosity 1\n"
    "\n"
    "# Full verbose output\n"
    "poetry run kpi-calculator --router n7k --os nxos \\\n"
    "                          --verbosity 3\n"
    "\n"
    "# Silent with JSON output only\n"
    "poetry run kpi-calculator --router n7k --os nxos \\\n"
    "                          --verbosity 0 \\\n"
    "                          --output-json results.json\n"
    "\n"
    "# Specific KPIs + JSON output\n"
    "poetry run kpi-calculator --router n7k --os nxos \\\n"
    "                          --kpis total_routes total_vrfs \\\n"
    "                          --output-json n7k_kpis.json\n"
    "\n"
    "# List available KPIs\n"
    "poetry run kpi-calculator --router n7k --os nxos \\\n"
    "                          --list-kpis\n"
    "```\n"
    "\n"
    "## Verbosity Levels\n"
    "\n"
    "```\n"
    "0 = silent   No console output\n"
    "1 = minimal  One line per KPI: name + value\n"
    "2 = normal   Condensed output (default)\n"
    "3 = verbose  Full output with breakdown\n"
    "```\n"
    "\n"
    "## JSON Output Format\n"
    "\n"
    "```json\n"
    "{\n"
    "  \"router\": \"n7k\",\n"
    "  \"os\": \"nxos\",\n"
    "  \"timestamp\": \"2026-04-07T10:22:01\",\n"
    "  \"kpis\": {\n"
    "    \"total_routes\": {\n"
    "      \"description\": \"Total number of IP routes\",\n"
    "      \"value\": 47,\n"
    "      \"status\": \"ok\",\n"
    "      \"operation\": \"sum\"\n"
    "    }\n"
    "  }\n"
    "}\n"
    "```\n"
    "\n"
    "## Input File Convention\n"
    "\n"
    "```\n"
    "<input_dir>/<router_name>__<show_command>.txt\n"
    "\n"
    "Default input_dir: input_files/\n"
    "\n"
    "NX-OS examples (n7k):\n"
    "  input_files/n7k__show_ip_route_summary.txt\n"
    "  input_files/n7k__show_mac_address-table.txt\n"
    "\n"
    "IOS-XE examples (cat9k):\n"
    "  input_files/cat9k__show_ip_route_summary.txt\n"
    "\n"
    "IOS-XR examples (asr9k):\n"
    "  input_files/asr9k__show_route_summary.txt\n"
    "```\n"
    "\n"
    "## Adding New KPIs\n"
    "\n"
    "Edit kpi_models.yaml only -- no Python changes needed.\n"
    "\n"
    "## License\n"
    "MIT\n"
)


GITIGNORE = """
# Python
__pycache__/
*.py[cod]
*.pyo
*.pyd
.Python
*.egg-info/
dist/
build/
.eggs/

# Poetry
.venv/

# PyCharm
.idea/

# Coverage
.coverage
htmlcov/

# MyPy
.mypy_cache/

# Ruff
.ruff_cache/

# Input files -- excluded from git
# Remove this line to commit sample input files
input_files/*.txt

# JSON output files -- excluded from git
# Remove this line to commit output files
*.json
"""


AI_SESSION_GUIDE_MD = (
    "# AI Session Guide -- pyats-kpi-calculator\n"
    "\n"
    "## Purpose\n"
    "\n"
    "Paste this document into a new AI session to provide full\n"
    "context for continuing development of pyats-kpi-calculator.\n"
    "\n"
    "---\n"
    "\n"
    "## Project Overview\n"
    "\n"
    "pyats-kpi-calculator is a Python CLI tool that extracts KPIs\n"
    "from offline Cisco device show command outputs using PyATS/Genie.\n"
    "\n"
    "### Core Principles\n"
    "- All files are exclusively AI-generated -- no manual edits\n"
    "- Changes applied via bootstrap_project.py\n"
    "- ai-bootstrap >= 0.2.0 manages git commits, file writing\n"
    "  and push to GitHub\n"
    "- KPI definitions live in kpi_models.yaml\n"
    "\n"
    "---\n"
    "\n"
    "## Tech Stack\n"
    "\n"
    "```toml\n"
    "python              = >=3.10,<4.0\n"
    "pyats               = >=23.0\n"
    "genie               = >=23.0\n"
    "genie.libs.parser   = >=23.0\n"
    "PyYAML              = >=6.0\n"
    "schema              = >=0.7.5\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## Platform Requirements\n"
    "\n"
    "PyATS runs on Linux/macOS/WSL2 only -- not native Windows.\n"
    "Ubuntu 24.04 LTS on WSL2 is the recommended dev environment.\n"
    "\n"
    "---\n"
    "\n"
    "## Generic Router Names\n"
    "\n"
    "Always use these generic names in code and documentation:\n"
    "  n7k    -- NX-OS  (e.g. Nexus 7000)\n"
    "  cat9k  -- IOS-XE (e.g. Catalyst 9000)\n"
    "  asr9k  -- IOS-XR (e.g. ASR 9000)\n"
    "Never use private or customer-specific names.\n"
    "\n"
    "---\n"
    "\n"
    "## Genie Parser Notes\n"
    "\n"
    "NX-OS parsers use output= not text= for offline parsing.\n"
    "Engine tries PARSE_PARAMS = ['output', 'text'] in order.\n"
    "\n"
    "Verified NX-OS parser locations:\n"
    "  show ip route summary  -> show_routing.ShowIpRouteSummary\n"
    "  show mac address-table -> show_fdb.ShowMacAddressTable\n"
    "  show bgp summary       -> show_bgp.ShowBgpSummary\n"
    "\n"
    "---\n"
    "\n"
    "## Bootstrap Setup\n"
    "\n"
    "ai-bootstrap installed in dedicated venv:\n"
    "  python3.11 -m venv ~/.bootstrap-venv\n"
    "  ~/.bootstrap-venv/bin/pip install ~/projects/ai-bootstrap\n"
    "\n"
    "Run bootstrap:\n"
    "  cd ~/projects/pyats-kpi-calculator\n"
    "  ~/.bootstrap-venv/bin/python bootstrap_project.py\n"
    "\n"
    "---\n"
    "\n"
    "## CLI Arguments\n"
    "\n"
    "  --router        Router name (required)\n"
    "  --os            OS type: nxos | iosxe | iosxr (required)\n"
    "  --kpis          Space-separated KPI names (optional, default: all)\n"
    "  --list-kpis     List available KPIs and exit\n"
    "  --input-dir     Input files directory (default: input_files)\n"
    "  --models        KPI models YAML file (default: kpi_models.yaml)\n"
    "  --verbosity     0=silent 1=minimal 2=normal 3=verbose (default: 2)\n"
    "  --output-json   Write results to JSON file\n"
    "\n"
    "---\n"
    "\n"
    "## Verbosity Levels\n"
    "\n"
    "  0 = silent   No console output\n"
    "  1 = minimal  One line per KPI: name + value\n"
    "  2 = normal   Condensed output (default)\n"
    "  3 = verbose  Full output with breakdown\n"
    "\n"
    "---\n"
    "\n"
    "## JSON Output Structure\n"
    "\n"
    "```json\n"
    "{\n"
    "  \"router\": \"<name>\",\n"
    "  \"os\": \"<os_type>\",\n"
    "  \"timestamp\": \"<ISO 8601>\",\n"
    "  \"kpis\": {\n"
    "    \"<kpi_name>\": {\n"
    "      \"description\": \"<str>\",\n"
    "      \"value\": <int>,\n"
    "      \"status\": \"ok|warning|error\",\n"
    "      \"operation\": \"<str>\"\n"
    "    }\n"
    "  }\n"
    "}\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## Input Files\n"
    "\n"
    "Default location: input_files/ directory\n"
    "Convention: <router_name>__<show_command_underscored>.txt\n"
    "Example: input_files/n7k__show_ip_route_summary.txt\n"
    "\n"
    "File encoding: utf-8 preferred.\n"
    "Engine also handles cp1252 and latin-1 automatically.\n"
    "\n"
    "---\n"
    "\n"
    "## Supported OS Types\n"
    "\n"
    "nxos | iosxe | iosxr\n"
    "\n"
    "---\n"
    "\n"
    "## Supported Operations\n"
    "\n"
    "sum | count | max | min | avg | sum_lengths\n"
    "\n"
    "---\n"
    "\n"
    "## KPI Model Structure\n"
    "\n"
    "```yaml\n"
    "<kpi_name>:\n"
    "  description: <str>\n"
    "  source:\n"
    "    <os_type>:\n"
    "      show_command:  <str>\n"
    "      parser_module: <str>\n"
    "      parser_class:  <str>\n"
    "  iterate:   <str or list>\n"
    "  value_key: <str>        # optional\n"
    "  operation: <str>\n"
    "  filter:                 # optional\n"
    "    key:   <str>\n"
    "    value: <str>\n"
    "  default: 0\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## Existing KPIs\n"
    "\n"
    "total_routes         -- sum of routes across all VRFs\n"
    "max_routes_in_vrf    -- max routes in a single VRF\n"
    "total_vrfs           -- count of VRFs\n"
    "total_mac_addresses  -- sum of MACs across all VLANs\n"
    "total_bgp_neighbors  -- count of BGP neighbors\n"
    "total_bgp_routes_rib -- sum of BGP prefixes received\n"
    "total_bfd_sessions_up   -- count of BFD sessions Up\n"
    "total_bfd_sessions_down -- count of BFD sessions Down\n"
    "\n"
    "---\n"
    "\n"
    "## Bootstrap File Rules\n"
    "\n"
    "1.  Always include ALL files in FILES dict\n"
    "2.  Always overwrite -- never skip or protect\n"
    "3.  Triple-quoted strings for .py .yaml .toml\n"
    "4.  Concatenated strings for .md with code blocks\n"
    "5.  Escape internal quotes as \\\"\n"
    "6.  Escape backslashes as \\\\\n"
    "7.  Escape newlines as \\\\n\n"
    "8.  End with if __name__ == '__main__': entry point\n"
    "9.  Use project_path='.'\n"
    "10. Use forward slashes in FILES keys\n"
    "11. Update feature_description each session\n"
    "12. Always include push=True, remote='origin', branch='main'\n"
    "13. Never use private names -- use n7k, cat9k, asr9k\n"
    "\n"
    "---\n"
    "\n"
    "## Context Block for New AI Session\n"
    "\n"
    "```\n"
    "I am working on pyats-kpi-calculator.\n"
    "All files are exclusively AI-generated.\n"
    "Changes applied via:\n"
    "  ~/.bootstrap-venv/bin/python bootstrap_project.py\n"
    "We use ai-bootstrap >= 0.2.0:\n"
    "  Bootstrap(project_path='.').run(\n"
    "      feature_description='<desc>',\n"
    "      files=FILES,\n"
    "      push=True,\n"
    "      remote='origin',\n"
    "      branch='main'\n"
    "  )\n"
    "Key files:\n"
    "  kpi_calculator.py    -- generic engine\n"
    "  kpi_models.yaml      -- KPI definitions\n"
    "  bootstrap_project.py -- master rebuild script\n"
    "Supported OS: nxos, iosxe, iosxr\n"
    "Operations: sum, count, max, min, avg, sum_lengths\n"
    "Input files: input_files/<router>__<command>.txt\n"
    "Genie NX-OS: PARSE_PARAMS=['output','text']\n"
    "             show_fdb.ShowMacAddressTable for MAC KPI\n"
    "CLI: --router --os --kpis --list-kpis --input-dir\n"
    "     --models --verbosity (0-3) --output-json\n"
    "JSON output: router, os, timestamp, kpis{}\n"
    "Generic names: n7k (nxos), cat9k (iosxe), asr9k (iosxr)\n"
    "pyproject.toml: packages=[{include='kpi_calculator.py'}]\n"
    "PyATS: Linux/macOS/WSL2 only\n"
    "Bootstrap venv: ~/.bootstrap-venv\n"
    "GitHub remote: origin/main\n"
    "Please provide updated bootstrap_project.py with:\n"
    "<DESCRIBE YOUR CHANGE HERE>\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## Version History\n"
    "\n"
    "| Version | Date       | Changes                                           |\n"
    "|---------|------------|---------------------------------------------------|\n"
    "| 0.1.0   | 2026-04-06 | Initial -- engine, 8 KPIs, schema validation      |\n"
    "| 0.1.1   | 2026-04-06 | Fix -- add packages directive to pyproject.toml   |\n"
    "| 0.1.2   | 2026-04-06 | Fix -- add input_files/ dir to file path          |\n"
    "| 0.1.3   | 2026-04-06 | Add -- push to GitHub via ai-bootstrap 0.2.0      |\n"
    "| 0.1.4   | 2026-04-07 | Fix -- use output= param, add encoding handling   |\n"
    "| 0.1.5   | 2026-04-07 | Add -- --kpis and --list-kpis CLI arguments       |\n"
    "| 0.1.6   | 2026-04-07 | Fix -- MAC parser module show_fdb not show_l2route|\n"
    "| 0.1.7   | 2026-04-07 | Fix -- replace private names with generic n7k     |\n"
    "| 0.1.8   | 2026-04-07 | Add -- verbosity levels and JSON output           |\n"
)


BOOTSTRAP_TEMPLATE_PY = """
# BOOTSTRAP_TEMPLATE.py
# pyats-kpi-calculator -- Template for AI update sessions
#
# INSTRUCTIONS FOR AI:
#   1. Start from latest bootstrap_project.py
#   2. Apply requested changes to relevant FILE variables
#   3. Update feature_description
#   4. Return complete updated bootstrap_project.py
#   5. Use only generic names: n7k, cat9k, asr9k

from ai_bootstrap import Bootstrap

PYPROJECT_TOML     = \"\"\"<content>\"\"\"
KPI_CALCULATOR_PY  = \"\"\"<content>\"\"\"
KPI_MODELS_YAML    = \"\"\"<content>\"\"\"
TEST_SCHEMA_PY     = \"\"\"<content>\"\"\"
TEST_CALCULATOR_PY = \"\"\"<content>\"\"\"
TEST_PARSER_PY     = \"\"\"<content>\"\"\"
README_MD               = "<content>"
GITIGNORE               = \"\"\"<content>\"\"\"
TESTS_INIT_PY           = ""
INPUT_FILES_GITKEEP     = ""
AI_SESSION_GUIDE_MD     = "<content>"
BOOTSTRAP_TEMPLATE_PY   = "<content>"

FILES = {
    "pyproject.toml":           PYPROJECT_TOML,
    "README.md":                README_MD,
    ".gitignore":               GITIGNORE,
    "kpi_calculator.py":        KPI_CALCULATOR_PY,
    "kpi_models.yaml":          KPI_MODELS_YAML,
    "tests/__init__.py":        TESTS_INIT_PY,
    "tests/test_schema.py":     TEST_SCHEMA_PY,
    "tests/test_calculator.py": TEST_CALCULATOR_PY,
    "tests/test_parser.py":     TEST_PARSER_PY,
    "input_files/.gitkeep":     INPUT_FILES_GITKEEP,
    "AI_SESSION_GUIDE.md":      AI_SESSION_GUIDE_MD,
    "BOOTSTRAP_TEMPLATE.py":    BOOTSTRAP_TEMPLATE_PY,
}

if __name__ == "__main__":
    Bootstrap(project_path=".").run(
        feature_description = "<describe what changed>",
        files               = FILES,
        push                = True,
        remote              = "origin",
        branch              = "main"
    )
"""


TESTS_INIT_PY       = ""
INPUT_FILES_GITKEEP = ""


# ===============================================================
# FILE MANIFEST
# ===============================================================

FILES = {
    "pyproject.toml":           PYPROJECT_TOML,
    "README.md":                README_MD,
    ".gitignore":               GITIGNORE,
    "kpi_calculator.py":        KPI_CALCULATOR_PY,
    "kpi_models.yaml":          KPI_MODELS_YAML,
    "tests/__init__.py":        TESTS_INIT_PY,
    "tests/test_schema.py":     TEST_SCHEMA_PY,
    "tests/test_calculator.py": TEST_CALCULATOR_PY,
    "tests/test_parser.py":     TEST_PARSER_PY,
    "input_files/.gitkeep":     INPUT_FILES_GITKEEP,
    "AI_SESSION_GUIDE.md":      AI_SESSION_GUIDE_MD,
    "BOOTSTRAP_TEMPLATE.py":    BOOTSTRAP_TEMPLATE_PY,
}


# ===============================================================
# ENTRY POINT
# ===============================================================

if __name__ == "__main__":
    Bootstrap(project_path=".").run(
        feature_description = "add verbosity levels and JSON output",
        files               = FILES,
        push                = True,
        remote              = "origin",
        branch              = "main"
    )