# bootstrap_project.py
# Generated by CircuIT — do not edit manually
#
# PURPOSE : Creates all source files for pyats-kpi-calculator
# USAGE   : python bootstrap_project.py
# NOTE    : Run from inside pyats-kpi-calculator/ directory

from ai_bootstrap import Bootstrap


# ===============================================================
# FILE CONTENTS
# ===============================================================

PYPROJECT_TOML = """
[tool.poetry]
name        = "pyats-kpi-calculator"
version     = "0.1.0"
description = "PyATS Offline KPI Calculator — Extract KPIs from captured NX-OS/IOS-XE/IOS-XR show command outputs"
readme      = "README.md"
packages    = [{include = "kpi_calculator.py"}]
keywords    = [
    "cisco",
    "pyats",
    "genie",
    "network-automation",
    "nxos",
    "iosxe",
    "iosxr",
    "kpi",
    "network-monitoring"
]

[tool.poetry.dependencies]
python              = ">=3.10,<4.0"
pyats               = ">=23.0"
genie               = ">=23.0"
"genie.libs.parser" = ">=23.0"
PyYAML              = ">=6.0"
schema              = ">=0.7.5"

[tool.poetry.group.dev.dependencies]
pytest        = ">=7.4"
pytest-cov    = ">=4.1"
ruff          = ">=0.1.0"
mypy          = ">=1.5"
types-PyYAML  = ">=6.0"

[tool.poetry.scripts]
kpi-calculator = "kpi_calculator:main"

[build-system]
requires      = ["poetry-core>=1.7.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
verbosity = 2
addopts   = "--cov=kpi_calculator --cov-report=term-missing"

[tool.ruff]
line-length    = 79
target-version = "py310"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "UP"]
ignore = ["E501"]

[tool.mypy]
python_version         = "3.10"
warn_return_any        = true
warn_unused_configs    = true
ignore_missing_imports = true
"""


KPI_CALCULATOR_PY = """
# kpi_calculator.py
# Generated by CircuIT — do not edit manually

import sys
import argparse
import importlib

import yaml
from schema import Schema, And, Or, Optional, SchemaError
from genie.conf.base import Device


# ---------------------------------------------------------------
# Constants
# ---------------------------------------------------------------

VALID_OPERATIONS = ["sum", "count", "max", "min", "avg", "sum_lengths"]
SUPPORTED_OS     = ["nxos", "iosxe", "iosxr"]
KPI_MODELS_FILE  = "kpi_models.yaml"


# ---------------------------------------------------------------
# Supported Operations Registry
# ---------------------------------------------------------------

OPERATIONS = {
    "sum":         lambda values: sum(values),
    "count":       lambda values: len(values),
    "max":         lambda values: max(values) if values else 0,
    "min":         lambda values: min(values) if values else 0,
    "avg":         lambda values: sum(values) / len(values) if values else 0,
    "sum_lengths": lambda values: sum(len(v) if isinstance(v, dict) else v
                                      for v in values)
}


# ---------------------------------------------------------------
# Schema Definitions
# ---------------------------------------------------------------

OS_SOURCE_SCHEMA = Schema({
    "show_command":  And(str, len,
                        error="show_command must be a non-empty string"),
    "parser_module": And(str, len,
                        error="parser_module must be a non-empty string"),
    "parser_class":  And(str, len,
                        error="parser_class must be a non-empty string")
})

FILTER_SCHEMA = Schema({
    "key":   And(str, len, error="filter.key must be a non-empty string"),
    "value": And(str, len, error="filter.value must be a non-empty string")
})

KPI_ENTRY_SCHEMA = Schema({
    "description": And(
        str, len,
        error="description must be a non-empty string"
    ),
    "source": And(
        dict,
        lambda s: len(s) > 0,
        lambda s: all(os_key in SUPPORTED_OS for os_key in s.keys()),
        lambda s: all(OS_SOURCE_SCHEMA.is_valid(v) for v in s.values()),
        error=(
            f"source must define at least one supported OS "
            f"{SUPPORTED_OS} with show_command, "
            f"parser_module and parser_class"
        )
    ),
    "iterate": Or(
        And(str, len),
        And(
            list,
            lambda l: len(l) > 0,
            lambda l: all(isinstance(i, str) and len(i) > 0 for i in l)
        ),
        error="iterate must be a non-empty string or list of strings"
    ),
    Optional("value_key"): And(
        str, len,
        error="value_key must be a non-empty string"
    ),
    "operation": And(
        str,
        lambda op: op in VALID_OPERATIONS,
        error=f"operation must be one of: {VALID_OPERATIONS}"
    ),
    Optional("filter"): And(
        dict,
        lambda f: FILTER_SCHEMA.is_valid(f),
        error="filter must have non-empty 'key' and 'value' fields"
    ),
    "default": And(
        int,
        lambda n: n >= 0,
        error="default must be a non-negative integer"
    )
})

KPI_MODELS_SCHEMA = Schema({
    And(str, len): KPI_ENTRY_SCHEMA
})


# ---------------------------------------------------------------
# CLI Argument Parser
# ---------------------------------------------------------------

def parse_arguments() -> argparse.Namespace:
    \"\"\"
    Parses CLI arguments.

    Usage:
      python kpi_calculator.py --router <router_name> --os <os_type>

    Examples:
      python kpi_calculator.py --router core-sw-01   --os nxos
      python kpi_calculator.py --router edge-rtr-02  --os iosxe
      python kpi_calculator.py --router pe-router-01 --os iosxr
    \"\"\"
    parser = argparse.ArgumentParser(
        description="PyATS Offline KPI Calculator"
    )
    parser.add_argument(
        "--router",
        required=True,
        help="Router name used to derive input file names."
    )
    parser.add_argument(
        "--os",
        required=True,
        choices=SUPPORTED_OS,
        help=f"Network OS type. Supported: {SUPPORTED_OS}"
    )
    parser.add_argument(
        "--models",
        default=KPI_MODELS_FILE,
        help=f"Path to KPI models YAML file. Default: {KPI_MODELS_FILE}"
    )
    return parser.parse_args()


# ---------------------------------------------------------------
# YAML Model Loader + Validator
# ---------------------------------------------------------------

def validate_kpi_models(models: dict) -> bool:
    \"\"\"
    Validates all KPI model entries individually, reporting
    a descriptive error for each failing KPI rather than
    stopping at the first failure.
    Returns True if all models are valid, False otherwise.
    \"\"\"
    all_valid = True
    for kpi_name, kpi_entry in models.items():
        try:
            KPI_ENTRY_SCHEMA.validate(kpi_entry)
        except SchemaError as e:
            print(f"  [FAIL] KPI '{kpi_name}': {e}")
            all_valid = False
    return all_valid


def load_kpi_models(filepath: str) -> dict:
    \"\"\"
    Loads KPI model definitions from YAML file and validates
    the complete structure. Reports all validation errors
    before exiting — not just the first one.
    \"\"\"
    try:
        with open(filepath, "r") as f:
            models = yaml.safe_load(f)
        if not isinstance(models, dict):
            print(f"[ERROR] KPI models file must contain "
                  f"a YAML dictionary at the top level.")
            sys.exit(1)
    except FileNotFoundError:
        print(f"[ERROR] KPI models file not found: '{filepath}'")
        sys.exit(1)
    except yaml.YAMLError as e:
        print(f"[ERROR] Failed to parse YAML file: {e}")
        sys.exit(1)

    print(f"[INFO] Validating KPI models from '{filepath}' ...")
    try:
        KPI_MODELS_SCHEMA.validate(models)
    except SchemaError as e:
        print(f"[ERROR] Top-level schema validation failed: {e}")
        sys.exit(1)

    print(f"[INFO] Validating {len(models)} KPI entries ...")
    if not validate_kpi_models(models):
        print(f"\\n[ERROR] One or more KPI models failed validation.")
        sys.exit(1)

    print(f"[INFO] Schema validation passed — "
          f"{len(models)} KPI models loaded.\\n")
    return models


# ---------------------------------------------------------------
# Dynamic Parser Class Resolver
# ---------------------------------------------------------------

def resolve_parser_class(parser_module: str, parser_class: str):
    \"\"\"
    Dynamically imports and returns a parser class using
    module path and class name strings from the YAML model.
    \"\"\"
    try:
        module = importlib.import_module(parser_module)
        return getattr(module, parser_class)
    except ModuleNotFoundError:
        print(f"[ERROR] Parser module not found: '{parser_module}'")
        sys.exit(1)
    except AttributeError:
        print(f"[ERROR] Parser class '{parser_class}' not found "
              f"in module '{parser_module}'")
        sys.exit(1)


# ---------------------------------------------------------------
# File Name Derivation
# ---------------------------------------------------------------

def derive_filename(router_name: str,
                    show_command: str,
                    extension: str = "txt") -> str:
    \"\"\"
    Derives input file name from router name and show command.
    Convention: <router_name>__<show_command_underscored>.<extension>
    \"\"\"
    command_part = show_command.lower().replace(" ", "_")
    return f"{router_name}__{command_part}.{extension}"


# ---------------------------------------------------------------
# Multi-Level Iterator
# ---------------------------------------------------------------

def collect_leaf_items(data: dict, keys: list) -> list:
    \"\"\"
    Recursively traverses nested dicts using a list of keys,
    collecting all leaf-level item dictionaries.
    \"\"\"
    if not keys:
        if isinstance(data, dict):
            return list(data.values())
        return []
    current_key = keys[0]
    remaining   = keys[1:]
    section     = data.get(current_key, {})
    leaf_items  = []
    for item_data in section.values():
        leaf_items.extend(collect_leaf_items(item_data, remaining))
    return leaf_items


# ---------------------------------------------------------------
# Dot-Notation Path Resolver
# ---------------------------------------------------------------

def resolve_path(data: dict, path: str) -> dict:
    \"\"\"
    Resolves a dot-notation string path into a nested dictionary.
    \"\"\"
    for key in path.split("."):
        if isinstance(data, dict):
            data = data.get(key, {})
        else:
            return {}
    return data


# ---------------------------------------------------------------
# Device Factory
# ---------------------------------------------------------------

def create_device(router_name: str, os_type: str) -> Device:
    device = Device(router_name, os=os_type)
    device.custom.setdefault("abstraction", {})["order"] = ["os"]
    return device


# ---------------------------------------------------------------
# File Reader
# ---------------------------------------------------------------

def read_input_file(filepath: str) -> str:
    try:
        with open(filepath, "r") as f:
            return f.read()
    except FileNotFoundError:
        print(f"[ERROR] File not found: '{filepath}' — "
              f"ensure file name matches convention: "
              f"<router_name>__<show_command>.txt")
        sys.exit(1)
    except IOError as e:
        print(f"[ERROR] Could not read file '{filepath}': {e}")
        sys.exit(1)


# ---------------------------------------------------------------
# Model-Driven Parser
# ---------------------------------------------------------------

def parse_output(model: dict,
                 router_name: str,
                 os_type: str,
                 parse_cache: dict) -> dict | None:
    \"\"\"
    Selects OS-specific show_command and parser_class from
    the YAML model, dynamically resolves the parser class,
    and performs offline parsing.
    Uses parse cache to avoid re-parsing the same file.
    \"\"\"
    source    = model.get("source", {})
    os_source = source.get(os_type)

    if not os_source:
        return None

    show_command  = os_source.get("show_command")
    parser_module = os_source.get("parser_module")
    parser_class  = os_source.get("parser_class")

    if not all([show_command, parser_module, parser_class]):
        print(f"[ERROR] Incomplete source entry for OS '{os_type}'.")
        sys.exit(1)

    input_file = derive_filename(router_name, show_command)

    if input_file in parse_cache:
        print(f"[CACHE] Using cached result for: '{input_file}'")
        return parse_cache[input_file]

    print(f"[INFO] Router  : '{router_name}'")
    print(f"[INFO] OS      : '{os_type}'")
    print(f"[INFO] Command : '{show_command}'")
    print(f"[INFO] File    : '{input_file}'")

    resolved_class = resolve_parser_class(parser_module, parser_class)
    device         = create_device(router_name, os_type)
    raw_output     = read_input_file(input_file)

    try:
        parser = resolved_class(device=device)
        parsed = parser.parse(text=raw_output)
        parse_cache[input_file] = parsed
        return parsed
    except Exception as e:
        print(f"[ERROR] Parsing failed for '{show_command}': {e}")
        sys.exit(1)


# ---------------------------------------------------------------
# Generic KPI Calculator
# ---------------------------------------------------------------

def calculate_kpi(model: dict, parsed_output: dict) -> dict:
    \"\"\"
    Generic KPI calculator supporting single-level and
    multi-level iteration with optional value filtering.
    \"\"\"
    iterate    = model.get("iterate")
    value_key  = model.get("value_key")
    operation  = model.get("operation", "sum")
    default    = model.get("default", 0)
    filter_def = model.get("filter")

    if operation not in OPERATIONS:
        return {
            "status":  "error",
            "message": f"Unsupported operation: '{operation}'. "
                       f"Supported: {VALID_OPERATIONS}"
        }

    if isinstance(iterate, list):
        leaf_items = collect_leaf_items(parsed_output, iterate)

        if not leaf_items:
            return {
                "status":      "warning",
                "description": model.get("description"),
                "value":       default,
                "message":     f"No data found at path: {iterate}"
            }

        if filter_def:
            filter_key   = filter_def.get("key")
            filter_value = filter_def.get("value")
            leaf_items   = [
                item for item in leaf_items
                if item.get(filter_key) == filter_value
            ]

        collected_values   = (
            [item.get(value_key, default) for item in leaf_items]
            if value_key else leaf_items
        )
        result_value       = OPERATIONS[operation](collected_values)
        per_item_breakdown = {"matched_items": len(leaf_items)}

    else:
        iterable_section = resolve_path(parsed_output, iterate)

        if not iterable_section:
            return {
                "status":      "warning",
                "description": model.get("description"),
                "value":       default,
                "message":     f"No data found at path: '{iterate}'"
            }

        collected_values   = []
        per_item_breakdown = {}

        for item_name, item_data in iterable_section.items():
            value = item_data.get(value_key, default)
            collected_values.append(value)
            per_item_breakdown[item_name] = (
                len(value) if isinstance(value, dict) else value
            )

        result_value = OPERATIONS[operation](collected_values)

    return {
        "status":      "ok",
        "description": model.get("description"),
        "operation":   operation,
        "value":       result_value,
        "breakdown":   per_item_breakdown
    }


# ---------------------------------------------------------------
# Output Formatting
# ---------------------------------------------------------------

def print_kpi_result(kpi_name: str,
                     model: dict,
                     result: dict,
                     router_name: str,
                     os_type: str) -> None:
    os_source    = model.get("source", {}).get(os_type, {})
    show_command = os_source.get("show_command", "N/A")
    input_file   = derive_filename(router_name, show_command)

    print("\\n" + "=" * 60)
    print(f"  KPI          : {kpi_name}")
    print("=" * 60)
    print(f"  Description  : {result.get('description')}")
    print(f"  Router       : {router_name}")
    print(f"  OS           : {os_type}")
    print(f"  Show Command : {show_command}")
    print(f"  Input File   : {input_file}  (auto-derived)")
    print(f"  Status       : {result.get('status')}")
    print(f"  Operation    : {result.get('operation')}")
    if model.get("filter"):
        f = model.get("filter")
        print(f"  Filter       : {f.get('key')} == '{f.get('value')}'")
    print(f"\\n  Breakdown:")
    for item, value in result.get("breakdown", {}).items():
        print(f"    {item:<25} : {value}")
    print(f"\\n  Result Value : {result.get('value')}")
    print("=" * 60 + "\\n")


# ---------------------------------------------------------------
# Main
# ---------------------------------------------------------------

def main():
    args        = parse_arguments()
    router_name = args.router
    os_type     = args.os
    models_file = args.models
    parse_cache = {}

    print(f"\\n{'=' * 60}")
    print(f"  PyATS Offline KPI Calculator")
    print(f"  Router     : {router_name}")
    print(f"  OS         : {os_type}")
    print(f"  Models File: {models_file}")
    print(f"{'=' * 60}\\n")

    kpi_models = load_kpi_models(models_file)

    for kpi_name, model in kpi_models.items():
        parsed_output = parse_output(
            model, router_name, os_type, parse_cache
        )
        if parsed_output is None:
            print(f"[SKIP] KPI '{kpi_name}' — "
                  f"OS '{os_type}' not supported.\\n")
            continue

        result = calculate_kpi(model, parsed_output)
        print_kpi_result(kpi_name, model, result, router_name, os_type)


if __name__ == "__main__":
    main()
"""


KPI_MODELS_YAML = """
total_routes:
  description: "Total number of IP routes across all VRFs"
  source:
    nxos:
      show_command:  "show ip route summary"
      parser_module: "genie.libs.parser.nxos.show_routing"
      parser_class:  "ShowIpRouteSummary"
    iosxe:
      show_command:  "show ip route summary"
      parser_module: "genie.libs.parser.iosxe.show_routing"
      parser_class:  "ShowIpRouteSummary"
    iosxr:
      show_command:  "show route summary"
      parser_module: "genie.libs.parser.iosxr.show_routing"
      parser_class:  "ShowRouteSummary"
  iterate:   "vrf"
  value_key: "total_routes"
  operation: "sum"
  default:   0

max_routes_in_vrf:
  description: "Highest route count found in a single VRF"
  source:
    nxos:
      show_command:  "show ip route summary"
      parser_module: "genie.libs.parser.nxos.show_routing"
      parser_class:  "ShowIpRouteSummary"
    iosxe:
      show_command:  "show ip route summary"
      parser_module: "genie.libs.parser.iosxe.show_routing"
      parser_class:  "ShowIpRouteSummary"
    iosxr:
      show_command:  "show route summary"
      parser_module: "genie.libs.parser.iosxr.show_routing"
      parser_class:  "ShowRouteSummary"
  iterate:   "vrf"
  value_key: "total_routes"
  operation: "max"
  default:   0

total_vrfs:
  description: "Total number of VRFs with routing information"
  source:
    nxos:
      show_command:  "show ip route summary"
      parser_module: "genie.libs.parser.nxos.show_routing"
      parser_class:  "ShowIpRouteSummary"
    iosxe:
      show_command:  "show ip route summary"
      parser_module: "genie.libs.parser.iosxe.show_routing"
      parser_class:  "ShowIpRouteSummary"
    iosxr:
      show_command:  "show route summary"
      parser_module: "genie.libs.parser.iosxr.show_routing"
      parser_class:  "ShowRouteSummary"
  iterate:   "vrf"
  value_key: "total_routes"
  operation: "count"
  default:   0

total_mac_addresses:
  description: "Total number of MAC addresses across all VLANs"
  source:
    nxos:
      show_command:  "show mac address-table"
      parser_module: "genie.libs.parser.nxos.show_l2route"
      parser_class:  "ShowMacAddressTable"
    iosxe:
      show_command:  "show mac address-table"
      parser_module: "genie.libs.parser.iosxe.show_l2"
      parser_class:  "ShowMacAddressTable"
  iterate:   "mac_table.vlans"
  value_key: "mac_addresses"
  operation: "sum_lengths"
  default:   0

total_bgp_neighbors:
  description: "Total number of BGP neighbors across all VRFs"
  source:
    nxos:
      show_command:  "show bgp summary"
      parser_module: "genie.libs.parser.nxos.show_bgp"
      parser_class:  "ShowBgpSummary"
    iosxe:
      show_command:  "show bgp summary"
      parser_module: "genie.libs.parser.iosxe.show_bgp"
      parser_class:  "ShowBgpSummary"
    iosxr:
      show_command:  "show bgp summary"
      parser_module: "genie.libs.parser.iosxr.show_bgp"
      parser_class:  "ShowBgpSummary"
  iterate:
    - "vrf"
    - "neighbor"
  operation: "count"
  default:   0

total_bgp_routes_rib:
  description: "Total BGP prefixes received across all VRFs, neighbors and address families"
  source:
    nxos:
      show_command:  "show bgp all summary"
      parser_module: "genie.libs.parser.nxos.show_bgp"
      parser_class:  "ShowBgpAllSummary"
    iosxe:
      show_command:  "show bgp all summary"
      parser_module: "genie.libs.parser.iosxe.show_bgp"
      parser_class:  "ShowBgpAllSummary"
    iosxr:
      show_command:  "show bgp all all summary"
      parser_module: "genie.libs.parser.iosxr.show_bgp"
      parser_class:  "ShowBgpAllAllSummary"
  iterate:
    - "vrf"
    - "neighbor"
    - "address_family"
  value_key: "prefixes_received"
  operation: "sum"
  default:   0

total_bfd_sessions_up:
  description: "Total number of BFD sessions in Up state"
  source:
    nxos:
      show_command:  "show bfd neighbors"
      parser_module: "genie.libs.parser.nxos.show_bfd"
      parser_class:  "ShowBfdNeighbors"
    iosxe:
      show_command:  "show bfd neighbors"
      parser_module: "genie.libs.parser.iosxe.show_bfd"
      parser_class:  "ShowBfdNeighbors"
    iosxr:
      show_command:  "show bfd all-interfaces"
      parser_module: "genie.libs.parser.iosxr.show_bfd"
      parser_class:  "ShowBfdAllInterfaces"
  iterate:
    - "our_address"
    - "neighbor_address"
  operation: "count"
  filter:
    key:   "state"
    value: "Up"
  default:   0

total_bfd_sessions_down:
  description: "Total number of BFD sessions in Down state"
  source:
    nxos:
      show_command:  "show bfd neighbors"
      parser_module: "genie.libs.parser.nxos.show_bfd"
      parser_class:  "ShowBfdNeighbors"
    iosxe:
      show_command:  "show bfd neighbors"
      parser_module: "genie.libs.parser.iosxe.show_bfd"
      parser_class:  "ShowBfdNeighbors"
    iosxr:
      show_command:  "show bfd all-interfaces"
      parser_module: "genie.libs.parser.iosxr.show_bfd"
      parser_class:  "ShowBfdAllInterfaces"
  iterate:
    - "our_address"
    - "neighbor_address"
  operation: "count"
  filter:
    key:   "state"
    value: "Down"
  default:   0
"""


TEST_SCHEMA_PY = """
# tests/test_schema.py
# Generated by CircuIT — do not edit manually

import pytest
from schema import SchemaError
from kpi_calculator import (
    KPI_MODELS_SCHEMA,
    KPI_ENTRY_SCHEMA,
    OS_SOURCE_SCHEMA,
    FILTER_SCHEMA,
    validate_kpi_models
)


def test_valid_os_source_passes():
    OS_SOURCE_SCHEMA.validate({
        "show_command":  "show ip route summary",
        "parser_module": "genie.libs.parser.nxos.show_routing",
        "parser_class":  "ShowIpRouteSummary"
    })


def test_os_source_missing_field_fails():
    with pytest.raises(SchemaError):
        OS_SOURCE_SCHEMA.validate({
            "show_command":  "show ip route summary",
            "parser_module": "genie.libs.parser.nxos.show_routing"
        })


def test_os_source_empty_string_fails():
    with pytest.raises(SchemaError):
        OS_SOURCE_SCHEMA.validate({
            "show_command":  "",
            "parser_module": "genie.libs.parser.nxos.show_routing",
            "parser_class":  "ShowIpRouteSummary"
        })


def test_valid_filter_passes():
    FILTER_SCHEMA.validate({"key": "state", "value": "Up"})


def test_filter_empty_value_fails():
    with pytest.raises(SchemaError):
        FILTER_SCHEMA.validate({"key": "state", "value": ""})


def test_filter_missing_key_fails():
    with pytest.raises(SchemaError):
        FILTER_SCHEMA.validate({"value": "Up"})


def test_valid_entry_passes():
    KPI_ENTRY_SCHEMA.validate({
        "description": "Total routes",
        "source": {
            "nxos": {
                "show_command":  "show ip route summary",
                "parser_module": "genie.libs.parser.nxos.show_routing",
                "parser_class":  "ShowIpRouteSummary"
            }
        },
        "iterate":   "vrf",
        "value_key": "total_routes",
        "operation": "sum",
        "default":   0
    })


def test_invalid_os_key_fails():
    with pytest.raises(SchemaError):
        KPI_ENTRY_SCHEMA.validate({
            "description": "Total routes",
            "source": {
                "invalid_os": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "sum",
            "default":   0
        })


def test_invalid_operation_fails():
    with pytest.raises(SchemaError):
        KPI_ENTRY_SCHEMA.validate({
            "description": "Total routes",
            "source": {
                "nxos": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "invalid_op",
            "default":   0
        })


def test_negative_default_fails():
    with pytest.raises(SchemaError):
        KPI_ENTRY_SCHEMA.validate({
            "description": "Total routes",
            "source": {
                "nxos": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "sum",
            "default":   -1
        })


def test_list_iterate_passes():
    KPI_ENTRY_SCHEMA.validate({
        "description": "BGP neighbors",
        "source": {
            "nxos": {
                "show_command":  "show bgp summary",
                "parser_module": "genie.libs.parser.nxos.show_bgp",
                "parser_class":  "ShowBgpSummary"
            }
        },
        "iterate":   ["vrf", "neighbor"],
        "operation": "count",
        "default":   0
    })


def test_empty_list_iterate_fails():
    with pytest.raises(SchemaError):
        KPI_ENTRY_SCHEMA.validate({
            "description": "BGP neighbors",
            "source": {
                "nxos": {
                    "show_command":  "show bgp summary",
                    "parser_module": "genie.libs.parser.nxos.show_bgp",
                    "parser_class":  "ShowBgpSummary"
                }
            },
            "iterate":   [],
            "operation": "count",
            "default":   0
        })


def test_empty_source_fails():
    with pytest.raises(SchemaError):
        KPI_ENTRY_SCHEMA.validate({
            "description": "Total routes",
            "source":      {},
            "iterate":     "vrf",
            "operation":   "sum",
            "default":     0
        })


def test_optional_value_key_absent_passes():
    KPI_ENTRY_SCHEMA.validate({
        "description": "BGP neighbors",
        "source": {
            "nxos": {
                "show_command":  "show bgp summary",
                "parser_module": "genie.libs.parser.nxos.show_bgp",
                "parser_class":  "ShowBgpSummary"
            }
        },
        "iterate":   ["vrf", "neighbor"],
        "operation": "count",
        "default":   0
    })


def test_validate_kpi_models_all_valid():
    models = {
        "kpi_one": {
            "description": "KPI one",
            "source": {
                "nxos": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "sum",
            "default":   0
        }
    }
    assert validate_kpi_models(models) is True


def test_validate_kpi_models_reports_all_failures():
    models = {
        "kpi_good": {
            "description": "Good KPI",
            "source": {
                "nxos": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "sum",
            "default":   0
        },
        "kpi_bad": {
            "description": "Bad KPI",
            "source": {
                "nxos": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "invalid_op",
            "default":   0
        }
    }
    assert validate_kpi_models(models) is False
"""


TEST_CALCULATOR_PY = """
# tests/test_calculator.py
# Generated by CircuIT — do not edit manually

import pytest
from kpi_calculator import calculate_kpi, collect_leaf_items, resolve_path


def test_resolve_path_single_key():
    data   = {"vrf": {"default": {"total_routes": 100}}}
    result = resolve_path(data, "vrf")
    assert "default" in result


def test_resolve_path_dot_notation():
    data   = {"mac_table": {"vlans": {"10": {"mac_addresses": {}}}}}
    result = resolve_path(data, "mac_table.vlans")
    assert "10" in result


def test_resolve_path_missing_key():
    data   = {"vrf": {}}
    result = resolve_path(data, "vrf.missing")
    assert result == {}


def test_collect_leaf_items_single_level():
    data = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5}
        }
    }
    items = collect_leaf_items(data, ["vrf"])
    assert len(items) == 2


def test_collect_leaf_items_two_levels():
    data = {
        "vrf": {
            "default": {
                "neighbor": {
                    "1.1.1.1": {"state": "Established"},
                    "2.2.2.2": {"state": "Established"}
                }
            }
        }
    }
    items = collect_leaf_items(data, ["vrf", "neighbor"])
    assert len(items) == 2


def test_calculate_kpi_sum():
    model  = {
        "description": "Total routes",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "sum",
        "default":     0
    }
    parsed = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5}
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 105


def test_calculate_kpi_count():
    model  = {
        "description": "Total VRFs",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "count",
        "default":     0
    }
    parsed = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5},
            "prod":    {"total_routes": 200}
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 3


def test_calculate_kpi_max():
    model  = {
        "description": "Max routes",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "max",
        "default":     0
    }
    parsed = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5},
            "prod":    {"total_routes": 200}
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 200


def test_calculate_kpi_with_filter():
    model  = {
        "description": "BFD Up",
        "iterate":     ["our_address", "neighbor_address"],
        "operation":   "count",
        "filter":      {"key": "state", "value": "Up"},
        "default":     0
    }
    parsed = {
        "our_address": {
            "10.0.0.1": {
                "neighbor_address": {
                    "10.0.0.2": {"state": "Up"},
                    "10.0.0.3": {"state": "Down"},
                    "10.0.0.4": {"state": "Up"}
                }
            }
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 2


def test_calculate_kpi_invalid_operation():
    model  = {
        "description": "Test",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "invalid",
        "default":     0
    }
    parsed = {"vrf": {"default": {"total_routes": 100}}}
    result = calculate_kpi(model, parsed)
    assert result["status"] == "error"


def test_calculate_kpi_empty_data():
    model  = {
        "description": "Test",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "sum",
        "default":     0
    }
    parsed = {"vrf": {}}
    result = calculate_kpi(model, parsed)
    assert result["status"] == "warning"
    assert result["value"]  == 0
"""


TEST_PARSER_PY = """
# tests/test_parser.py
# Generated by CircuIT — do not edit manually

import pytest
from kpi_calculator import derive_filename, resolve_parser_class


def test_derive_filename_basic():
    result = derive_filename("core-sw-01", "show ip route summary")
    assert result == "core-sw-01__show_ip_route_summary.txt"


def test_derive_filename_with_hyphen():
    result = derive_filename("core-sw-01", "show mac address-table")
    assert result == "core-sw-01__show_mac_address-table.txt"


def test_derive_filename_iosxr_command():
    result = derive_filename("pe-router-01", "show route summary")
    assert result == "pe-router-01__show_route_summary.txt"


def test_derive_filename_custom_extension():
    result = derive_filename(
        "core-sw-01", "show ip route summary", extension="log"
    )
    assert result == "core-sw-01__show_ip_route_summary.log"


def test_resolve_valid_parser_class():
    cls = resolve_parser_class(
        "genie.libs.parser.nxos.show_routing",
        "ShowIpRouteSummary"
    )
    assert cls is not None


def test_resolve_invalid_module():
    with pytest.raises(SystemExit):
        resolve_parser_class(
            "genie.libs.parser.nxos.nonexistent_module",
            "ShowIpRouteSummary"
        )


def test_resolve_invalid_class():
    with pytest.raises(SystemExit):
        resolve_parser_class(
            "genie.libs.parser.nxos.show_routing",
            "NonExistentClass"
        )
"""


README_MD = (
    "# pyats-kpi-calculator\n"
    "\n"
    "PyATS Offline KPI Calculator — Extract KPIs from captured\n"
    "NX-OS, IOS-XE and IOS-XR show command outputs.\n"
    "\n"
    "## Installation\n"
    "\n"
    "```bash\n"
    "poetry install\n"
    "```\n"
    "\n"
    "## Usage\n"
    "\n"
    "```bash\n"
    "poetry run kpi-calculator --router core-sw-01 --os nxos\n"
    "poetry run kpi-calculator --router edge-rtr-02 --os iosxe\n"
    "poetry run kpi-calculator --router pe-router-01 --os iosxr\n"
    "```\n"
    "\n"
    "## Input File Convention\n"
    "\n"
    "```\n"
    "<router_name>__<show_command>.txt\n"
    "\n"
    "Examples:\n"
    "  core-sw-01__show_ip_route_summary.txt\n"
    "  core-sw-01__show_bgp_summary.txt\n"
    "  pe-router-01__show_route_summary.txt\n"
    "```\n"
    "\n"
    "## Adding New KPIs\n"
    "\n"
    "Edit kpi_models.yaml only — no Python changes needed.\n"
    "\n"
    "## License\n"
    "MIT\n"
)


GITIGNORE = """
# Python
__pycache__/
*.py[cod]
*.pyo
*.pyd
.Python
*.egg-info/
dist/
build/
.eggs/

# Poetry
.venv/

# PyCharm
.idea/

# Coverage
.coverage
htmlcov/

# MyPy
.mypy_cache/

# Ruff
.ruff_cache/

# Input files — excluded from git
# Remove this line to commit sample input files
input_files/*.txt
"""


AI_SESSION_GUIDE_MD = (
    "# AI Session Guide — pyats-kpi-calculator\n"
    "\n"
    "## Purpose\n"
    "\n"
    "Paste this document into a new AI session to provide full\n"
    "context for continuing development of pyats-kpi-calculator.\n"
    "\n"
    "---\n"
    "\n"
    "## Project Overview\n"
    "\n"
    "pyats-kpi-calculator is a Python CLI tool that extracts KPIs\n"
    "from offline Cisco device show command outputs using PyATS/Genie.\n"
    "\n"
    "### Core Principles\n"
    "- All files are exclusively AI-generated — no manual edits\n"
    "- Changes applied via: python bootstrap_project.py\n"
    "- ai-bootstrap library manages git commits and file writing\n"
    "- KPI definitions live in kpi_models.yaml\n"
    "\n"
    "---\n"
    "\n"
    "## Tech Stack\n"
    "\n"
    "```toml\n"
    "python              = >=3.10,<4.0\n"
    "pyats               = >=23.0\n"
    "genie               = >=23.0\n"
    "genie.libs.parser   = >=23.0\n"
    "PyYAML              = >=6.0\n"
    "schema              = >=0.7.5\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## pyproject.toml — packages directive\n"
    "\n"
    "Project uses single-file module structure.\n"
    "packages directive is required in pyproject.toml:\n"
    "\n"
    "```toml\n"
    "packages = [{include = \"kpi_calculator.py\"}]\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## Platform Requirements\n"
    "\n"
    "PyATS is NOT supported on Windows.\n"
    "Supported platforms: Linux, macOS, WSL2.\n"
    "Recommended for Windows users: WSL2 + PyCharm WSL interpreter.\n"
    "\n"
    "---\n"
    "\n"
    "## Supported OS Types\n"
    "\n"
    "nxos | iosxe | iosxr\n"
    "\n"
    "---\n"
    "\n"
    "## Supported Operations\n"
    "\n"
    "sum | count | max | min | avg | sum_lengths\n"
    "\n"
    "---\n"
    "\n"
    "## KPI Model Structure\n"
    "\n"
    "```yaml\n"
    "<kpi_name>:\n"
    "  description: <str>\n"
    "  source:\n"
    "    <os_type>:\n"
    "      show_command:  <str>\n"
    "      parser_module: <str>\n"
    "      parser_class:  <str>\n"
    "  iterate:   <str or list>\n"
    "  value_key: <str>        # optional\n"
    "  operation: <str>\n"
    "  filter:                 # optional\n"
    "    key:   <str>\n"
    "    value: <str>\n"
    "  default: 0\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## File Naming Convention\n"
    "\n"
    "<router_name>__<show_command_underscored>.txt\n"
    "Example: core-sw-01__show_ip_route_summary.txt\n"
    "\n"
    "---\n"
    "\n"
    "## Bootstrap Workflow\n"
    "\n"
    "```bash\n"
    "python bootstrap_project.py\n"
    "poetry install\n"
    "poetry run pytest\n"
    "git log --oneline\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## Bootstrap File Rules\n"
    "\n"
    "1.  Always include ALL files in FILES dict\n"
    "2.  Always overwrite — never skip or protect\n"
    "3.  Triple-quoted strings for .py .yaml .toml\n"
    "4.  Concatenated strings for .md with code blocks\n"
    "5.  Escape internal quotes as \\\"\n"
    "6.  Escape backslashes as \\\\\n"
    "7.  Escape newlines as \\\\n\n"
    "8.  End with if __name__ == '__main__': entry point\n"
    "9.  Use project_path='.'\n"
    "10. Use forward slashes in FILES keys\n"
    "11. Update feature_description each session\n"
    "\n"
    "---\n"
    "\n"
    "## Existing KPIs\n"
    "\n"
    "total_routes         — sum of routes across all VRFs\n"
    "max_routes_in_vrf    — max routes in a single VRF\n"
    "total_vrfs           — count of VRFs\n"
    "total_mac_addresses  — sum of MACs across all VLANs\n"
    "total_bgp_neighbors  — count of BGP neighbors\n"
    "total_bgp_routes_rib — sum of BGP prefixes received\n"
    "total_bfd_sessions_up   — count of BFD sessions Up\n"
    "total_bfd_sessions_down — count of BFD sessions Down\n"
    "\n"
    "---\n"
    "\n"
    "## Context Block for New AI Session\n"
    "\n"
    "```\n"
    "I am working on pyats-kpi-calculator.\n"
    "All files are exclusively AI-generated.\n"
    "Changes applied via: python bootstrap_project.py\n"
    "We use ai-bootstrap library:\n"
    "  Bootstrap(project_path='.').run(\n"
    "      feature_description='<desc>', files=FILES)\n"
    "Key files:\n"
    "  kpi_calculator.py  — generic engine\n"
    "  kpi_models.yaml    — KPI definitions\n"
    "  bootstrap_project.py — master rebuild script\n"
    "Supported OS: nxos, iosxe, iosxr\n"
    "Operations: sum, count, max, min, avg, sum_lengths\n"
    "File convention: <router>__<command>.txt\n"
    "pyproject.toml requires: packages=[{include='kpi_calculator.py'}]\n"
    "PyATS runs on Linux/macOS/WSL2 only — not native Windows\n"
    "Please provide updated bootstrap_project.py with:\n"
    "<DESCRIBE YOUR CHANGE HERE>\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## Version History\n"
    "\n"
    "| Version | Date       | Changes                                           |\n"
    "|---------|------------|---------------------------------------------------|\n"
    "| 0.1.0   | 2026-04-06 | Initial — engine, 8 KPIs, schema validation       |\n"
    "| 0.1.1   | 2026-04-06 | Fix — add packages directive to pyproject.toml    |\n"
)


BOOTSTRAP_TEMPLATE_PY = """
# BOOTSTRAP_TEMPLATE.py
# pyats-kpi-calculator — Template for AI update sessions
#
# INSTRUCTIONS FOR AI:
#   1. Start from latest bootstrap_project.py
#   2. Apply requested changes to relevant FILE variables
#   3. Update feature_description to describe the change
#   4. Return complete updated bootstrap_project.py
#
# INSTRUCTIONS FOR HUMAN:
#   1. Replace bootstrap_project.py with version from AI
#   2. python bootstrap_project.py
#   3. poetry install  (if pyproject.toml changed)
#   4. poetry run pytest
#   5. git log --oneline

from ai_bootstrap import Bootstrap

PYPROJECT_TOML     = \"\"\"<content>\"\"\"
KPI_CALCULATOR_PY  = \"\"\"<content>\"\"\"
KPI_MODELS_YAML    = \"\"\"<content>\"\"\"
TEST_SCHEMA_PY     = \"\"\"<content>\"\"\"
TEST_CALCULATOR_PY = \"\"\"<content>\"\"\"
TEST_PARSER_PY     = \"\"\"<content>\"\"\"
README_MD          = "<content>"
GITIGNORE          = \"\"\"<content>\"\"\"
TESTS_INIT_PY           = ""
INPUT_FILES_GITKEEP     = ""
AI_SESSION_GUIDE_MD     = "<content>"
BOOTSTRAP_TEMPLATE_PY   = "<content>"

FILES = {
    "pyproject.toml":           PYPROJECT_TOML,
    "README.md":                README_MD,
    ".gitignore":               GITIGNORE,
    "kpi_calculator.py":        KPI_CALCULATOR_PY,
    "kpi_models.yaml":          KPI_MODELS_YAML,
    "tests/__init__.py":        TESTS_INIT_PY,
    "tests/test_schema.py":     TEST_SCHEMA_PY,
    "tests/test_calculator.py": TEST_CALCULATOR_PY,
    "tests/test_parser.py":     TEST_PARSER_PY,
    "input_files/.gitkeep":     INPUT_FILES_GITKEEP,
    "AI_SESSION_GUIDE.md":      AI_SESSION_GUIDE_MD,
    "BOOTSTRAP_TEMPLATE.py":    BOOTSTRAP_TEMPLATE_PY,
}

if __name__ == "__main__":
    Bootstrap(project_path=".").run(
        feature_description = "<describe what changed>",
        files               = FILES
    )
"""


TESTS_INIT_PY       = ""
INPUT_FILES_GITKEEP = ""


# ===============================================================
# FILE MANIFEST
# ===============================================================

FILES = {
    "pyproject.toml":           PYPROJECT_TOML,
    "README.md":                README_MD,
    ".gitignore":               GITIGNORE,
    "kpi_calculator.py":        KPI_CALCULATOR_PY,
    "kpi_models.yaml":          KPI_MODELS_YAML,
    "tests/__init__.py":        TESTS_INIT_PY,
    "tests/test_schema.py":     TEST_SCHEMA_PY,
    "tests/test_calculator.py": TEST_CALCULATOR_PY,
    "tests/test_parser.py":     TEST_PARSER_PY,
    "input_files/.gitkeep":     INPUT_FILES_GITKEEP,
    "AI_SESSION_GUIDE.md":      AI_SESSION_GUIDE_MD,
    "BOOTSTRAP_TEMPLATE.py":    BOOTSTRAP_TEMPLATE_PY,
}


# ===============================================================
# ENTRY POINT
# ===============================================================

if __name__ == "__main__":
    Bootstrap(project_path=".").run(
        feature_description = "fix pyproject.toml packages directive",
        files               = FILES
    )