# kpi_calculator.py
# Generated by CircuIT — do not edit manually

import os
import sys
import argparse
import importlib

import yaml
from schema import Schema, And, Or, Optional, SchemaError
from genie.conf.base import Device


# ---------------------------------------------------------------
# Constants
# ---------------------------------------------------------------

VALID_OPERATIONS  = ["sum", "count", "max", "min", "avg", "sum_lengths"]
SUPPORTED_OS      = ["nxos", "iosxe", "iosxr"]
KPI_MODELS_FILE   = "kpi_models.yaml"
DEFAULT_INPUT_DIR = "input_files"

# Genie parser parameter names to try in order
# output= works with NX-OS parsers in current Genie version
# text= is tried as fallback for other versions
PARSE_PARAMS = ["output", "text"]


# ---------------------------------------------------------------
# Supported Operations Registry
# ---------------------------------------------------------------

OPERATIONS = {
    "sum":         lambda values: sum(values),
    "count":       lambda values: len(values),
    "max":         lambda values: max(values) if values else 0,
    "min":         lambda values: min(values) if values else 0,
    "avg":         lambda values: sum(values) / len(values) if values else 0,
    "sum_lengths": lambda values: sum(len(v) if isinstance(v, dict) else v
                                      for v in values)
}


# ---------------------------------------------------------------
# Schema Definitions
# ---------------------------------------------------------------

OS_SOURCE_SCHEMA = Schema({
    "show_command":  And(str, len,
                        error="show_command must be a non-empty string"),
    "parser_module": And(str, len,
                        error="parser_module must be a non-empty string"),
    "parser_class":  And(str, len,
                        error="parser_class must be a non-empty string")
})

FILTER_SCHEMA = Schema({
    "key":   And(str, len, error="filter.key must be a non-empty string"),
    "value": And(str, len, error="filter.value must be a non-empty string")
})

KPI_ENTRY_SCHEMA = Schema({
    "description": And(
        str, len,
        error="description must be a non-empty string"
    ),
    "source": And(
        dict,
        lambda s: len(s) > 0,
        lambda s: all(os_key in SUPPORTED_OS for os_key in s.keys()),
        lambda s: all(OS_SOURCE_SCHEMA.is_valid(v) for v in s.values()),
        error=(
            f"source must define at least one supported OS "
            f"{SUPPORTED_OS} with show_command, "
            f"parser_module and parser_class"
        )
    ),
    "iterate": Or(
        And(str, len),
        And(
            list,
            lambda l: len(l) > 0,
            lambda l: all(isinstance(i, str) and len(i) > 0 for i in l)
        ),
        error="iterate must be a non-empty string or list of strings"
    ),
    Optional("value_key"): And(
        str, len,
        error="value_key must be a non-empty string"
    ),
    "operation": And(
        str,
        lambda op: op in VALID_OPERATIONS,
        error=f"operation must be one of: {VALID_OPERATIONS}"
    ),
    Optional("filter"): And(
        dict,
        lambda f: FILTER_SCHEMA.is_valid(f),
        error="filter must have non-empty 'key' and 'value' fields"
    ),
    "default": And(
        int,
        lambda n: n >= 0,
        error="default must be a non-negative integer"
    )
})

KPI_MODELS_SCHEMA = Schema({
    And(str, len): KPI_ENTRY_SCHEMA
})


# ---------------------------------------------------------------
# CLI Argument Parser
# ---------------------------------------------------------------

def parse_arguments() -> argparse.Namespace:
    """
    Parses CLI arguments.

    Usage:
      python kpi_calculator.py --router <name> --os <os_type>
                               [--kpis KPI1 KPI2 ...]
                               [--input-dir <dir>]
                               [--models <file>]
                               [--list-kpis]

    Examples:
      # Run all KPIs
      python kpi_calculator.py --router LaMSC1DC01 --os nxos

      # List available KPIs
      python kpi_calculator.py --router LaMSC1DC01 --os nxos
          --list-kpis

      # Run specific KPIs only
      python kpi_calculator.py --router LaMSC1DC01 --os nxos
          --kpis total_routes total_vrfs
    """
    parser = argparse.ArgumentParser(
        description="PyATS Offline KPI Calculator",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--router",
        required=True,
        help="Router name used to derive input file names."
    )
    parser.add_argument(
        "--os",
        required=True,
        choices=SUPPORTED_OS,
        help=f"Network OS type. Supported: {SUPPORTED_OS}"
    )
    parser.add_argument(
        "--models",
        default=KPI_MODELS_FILE,
        help=f"Path to KPI models YAML file. "
             f"Default: {KPI_MODELS_FILE}"
    )
    parser.add_argument(
        "--input-dir",
        default=DEFAULT_INPUT_DIR,
        dest="input_dir",
        help=f"Directory containing show command output files. "
             f"Default: {DEFAULT_INPUT_DIR}"
    )
    parser.add_argument(
        "--kpis",
        nargs="+",
        default=None,
        metavar="KPI_NAME",
        help=(
            "Space-separated list of KPI names to calculate. "
            "If not specified all KPIs are calculated. "
            "Example: --kpis total_routes total_vrfs"
        )
    )
    parser.add_argument(
        "--list-kpis",
        action="store_true",
        default=False,
        dest="list_kpis",
        help="List all available KPI names and exit."
    )
    return parser.parse_args()


# ---------------------------------------------------------------
# YAML Model Loader + Validator
# ---------------------------------------------------------------

def validate_kpi_models(models: dict) -> bool:
    """
    Validates all KPI model entries individually.
    Returns True if all models are valid, False otherwise.
    """
    all_valid = True
    for kpi_name, kpi_entry in models.items():
        try:
            KPI_ENTRY_SCHEMA.validate(kpi_entry)
        except SchemaError as e:
            print(f"  [FAIL] KPI '{kpi_name}': {e}")
            all_valid = False
    return all_valid


def load_kpi_models(filepath: str) -> dict:
    """
    Loads KPI model definitions from YAML file and validates
    the complete structure.
    """
    try:
        with open(filepath, "r") as f:
            models = yaml.safe_load(f)
        if not isinstance(models, dict):
            print(f"[ERROR] KPI models file must contain "
                  f"a YAML dictionary at the top level.")
            sys.exit(1)
    except FileNotFoundError:
        print(f"[ERROR] KPI models file not found: '{filepath}'")
        sys.exit(1)
    except yaml.YAMLError as e:
        print(f"[ERROR] Failed to parse YAML file: {e}")
        sys.exit(1)

    print(f"[INFO] Validating KPI models from '{filepath}' ...")
    try:
        KPI_MODELS_SCHEMA.validate(models)
    except SchemaError as e:
        print(f"[ERROR] Top-level schema validation failed: {e}")
        sys.exit(1)

    print(f"[INFO] Validating {len(models)} KPI entries ...")
    if not validate_kpi_models(models):
        print(f"\n[ERROR] One or more KPI models failed validation.")
        sys.exit(1)

    print(f"[INFO] Schema validation passed — "
          f"{len(models)} KPI models loaded.\n")
    return models


# ---------------------------------------------------------------
# KPI Selection
# ---------------------------------------------------------------

def select_kpis(kpi_models: dict,
                requested:  list | None) -> dict:
    """
    Filters KPI models to only the requested KPIs.
    If requested is None returns all KPIs unchanged.
    """
    if requested is None:
        return kpi_models

    available     = set(kpi_models.keys())
    requested_set = set(requested)
    not_found     = requested_set - available

    if not_found:
        print(f"\n[ERROR] Unknown KPI name(s): "
              f"{sorted(not_found)}")
        print(f"\n  Available KPIs in '{KPI_MODELS_FILE}':")
        for name in sorted(available):
            desc = kpi_models[name].get("description", "")
            print(f"    {name:<30} -- {desc}")
        print()
        sys.exit(1)

    return {
        name: model
        for name, model in kpi_models.items()
        if name in requested_set
    }


def list_kpis(kpi_models: dict) -> None:
    """
    Prints all available KPI names and descriptions then exits.
    """
    print(f"\n  Available KPIs ({len(kpi_models)} total):\n")
    print(f"  {'KPI Name':<35} Description")
    print(f"  {'-' * 35} {'-' * 40}")
    for name, model in kpi_models.items():
        desc = model.get("description", "")
        print(f"  {name:<35} {desc}")
    print()


# ---------------------------------------------------------------
# Dynamic Parser Class Resolver
# ---------------------------------------------------------------

def resolve_parser_class(parser_module: str, parser_class: str):
    """
    Dynamically imports and returns a parser class.
    """
    try:
        module = importlib.import_module(parser_module)
        return getattr(module, parser_class)
    except ModuleNotFoundError:
        print(f"[ERROR] Parser module not found: '{parser_module}'")
        sys.exit(1)
    except AttributeError:
        print(f"[ERROR] Parser class '{parser_class}' not found "
              f"in module '{parser_module}'")
        sys.exit(1)


# ---------------------------------------------------------------
# File Name Derivation
# ---------------------------------------------------------------

def derive_filename(router_name: str,
                    show_command: str,
                    input_dir: str = DEFAULT_INPUT_DIR,
                    extension: str = "txt") -> str:
    """
    Derives full input file path from router name,
    show command and input directory.

    Convention:
      <input_dir>/<router_name>__<show_command_underscored>.<ext>
    """
    command_part = show_command.lower().replace(" ", "_")
    filename     = f"{router_name}__{command_part}.{extension}"
    return os.path.join(input_dir, filename)


# ---------------------------------------------------------------
# Multi-Level Iterator
# ---------------------------------------------------------------

def collect_leaf_items(data: dict, keys: list) -> list:
    """
    Recursively traverses nested dicts using a list of keys,
    collecting all leaf-level item dictionaries.
    """
    if not keys:
        if isinstance(data, dict):
            return list(data.values())
        return []
    current_key = keys[0]
    remaining   = keys[1:]
    section     = data.get(current_key, {})
    leaf_items  = []
    for item_data in section.values():
        leaf_items.extend(collect_leaf_items(item_data, remaining))
    return leaf_items


# ---------------------------------------------------------------
# Dot-Notation Path Resolver
# ---------------------------------------------------------------

def resolve_path(data: dict, path: str) -> dict:
    """
    Resolves a dot-notation string path into a nested dictionary.
    """
    for key in path.split("."):
        if isinstance(data, dict):
            data = data.get(key, {})
        else:
            return {}
    return data


# ---------------------------------------------------------------
# Device Factory
# ---------------------------------------------------------------

def create_device(router_name: str, os_type: str) -> Device:
    device = Device(router_name, os=os_type)
    device.custom.setdefault("abstraction", {})["order"] = ["os"]
    return device


# ---------------------------------------------------------------
# File Reader
# ---------------------------------------------------------------

def read_input_file(filepath: str) -> str:
    """
    Reads raw CLI output from file.
    Tries multiple encodings to handle files captured
    from different platforms and tools.
    """
    encodings = ["utf-8", "cp1252", "latin-1"]

    for encoding in encodings:
        try:
            with open(filepath, "r", encoding=encoding) as f:
                content = f.read()
            if encoding != "utf-8":
                print(f"[INFO] File '{filepath}' read "
                      f"using encoding: {encoding}")
            return content
        except UnicodeDecodeError:
            continue
        except FileNotFoundError:
            print(f"[ERROR] File not found: '{filepath}'")
            print(f"        Expected convention: "
                  f"<input_dir>/<router>__<show_command>.txt")
            print(f"        Check --input-dir argument "
                  f"(default: {DEFAULT_INPUT_DIR})")
            sys.exit(1)
        except IOError as e:
            print(f"[ERROR] Could not read file '{filepath}': {e}")
            sys.exit(1)

    print(f"[ERROR] Could not decode '{filepath}' "
          f"with any supported encoding: {encodings}")
    sys.exit(1)


# ---------------------------------------------------------------
# Genie Parser -- Try Multiple Parameter Names
# ---------------------------------------------------------------

def _try_parse(parser_class,
               device,
               raw_output: str,
               show_command: str) -> dict:
    """
    Attempts offline parsing trying parameter names in the
    order defined by PARSE_PARAMS constant.
    """
    parser = parser_class(device=device)
    errors = []

    for param_name in PARSE_PARAMS:
        try:
            result = parser.parse(**{param_name: raw_output})
            print(f"[INFO] Parsed using {param_name}= parameter")
            return result
        except TypeError as e:
            errors.append(f"{param_name}= : {e}")
            continue
        except Exception as e:
            print(f"[ERROR] Parsing failed for '{show_command}': {e}")
            print(f"        Parser  : {parser_class.__name__}")
            print(f"        Param   : {param_name}=")
            sys.exit(1)

    print(f"[ERROR] Could not find working parse parameter "
          f"for '{show_command}'")
    print(f"        Parser : {parser_class.__name__}")
    print(f"        Tried  : {PARSE_PARAMS}")
    for err in errors:
        print(f"        {err}")
    sys.exit(1)


# ---------------------------------------------------------------
# Model-Driven Parser
# ---------------------------------------------------------------

def parse_output(model: dict,
                 router_name: str,
                 os_type: str,
                 input_dir: str,
                 parse_cache: dict) -> dict | None:
    """
    Selects OS-specific show_command and parser_class from
    the YAML model, dynamically resolves the parser class,
    and performs offline parsing.
    Uses parse cache to avoid re-parsing the same file.
    """
    source    = model.get("source", {})
    os_source = source.get(os_type)

    if not os_source:
        return None

    show_command  = os_source.get("show_command")
    parser_module = os_source.get("parser_module")
    parser_class  = os_source.get("parser_class")

    if not all([show_command, parser_module, parser_class]):
        print(f"[ERROR] Incomplete source entry for OS '{os_type}'.")
        sys.exit(1)

    input_file = derive_filename(router_name, show_command, input_dir)

    if input_file in parse_cache:
        print(f"[CACHE] Using cached result for: '{input_file}'")
        return parse_cache[input_file]

    print(f"[INFO] Router    : '{router_name}'")
    print(f"[INFO] OS        : '{os_type}'")
    print(f"[INFO] Command   : '{show_command}'")
    print(f"[INFO] Input dir : '{input_dir}'")
    print(f"[INFO] File      : '{input_file}'")

    resolved_class = resolve_parser_class(parser_module, parser_class)
    device         = create_device(router_name, os_type)
    raw_output     = read_input_file(input_file)

    parsed = _try_parse(
        resolved_class, device, raw_output, show_command
    )
    parse_cache[input_file] = parsed
    return parsed


# ---------------------------------------------------------------
# Generic KPI Calculator
# ---------------------------------------------------------------

def calculate_kpi(model: dict, parsed_output: dict) -> dict:
    """
    Generic KPI calculator supporting single-level and
    multi-level iteration with optional value filtering.
    """
    iterate    = model.get("iterate")
    value_key  = model.get("value_key")
    operation  = model.get("operation", "sum")
    default    = model.get("default", 0)
    filter_def = model.get("filter")

    if operation not in OPERATIONS:
        return {
            "status":  "error",
            "message": f"Unsupported operation: '{operation}'. "
                       f"Supported: {VALID_OPERATIONS}"
        }

    if isinstance(iterate, list):
        leaf_items = collect_leaf_items(parsed_output, iterate)

        if not leaf_items:
            return {
                "status":      "warning",
                "description": model.get("description"),
                "value":       default,
                "message":     f"No data found at path: {iterate}"
            }

        if filter_def:
            filter_key   = filter_def.get("key")
            filter_value = filter_def.get("value")
            leaf_items   = [
                item for item in leaf_items
                if item.get(filter_key) == filter_value
            ]

        collected_values   = (
            [item.get(value_key, default) for item in leaf_items]
            if value_key else leaf_items
        )
        result_value       = OPERATIONS[operation](collected_values)
        per_item_breakdown = {"matched_items": len(leaf_items)}

    else:
        iterable_section = resolve_path(parsed_output, iterate)

        if not iterable_section:
            return {
                "status":      "warning",
                "description": model.get("description"),
                "value":       default,
                "message":     f"No data found at path: '{iterate}'"
            }

        collected_values   = []
        per_item_breakdown = {}

        for item_name, item_data in iterable_section.items():
            value = item_data.get(value_key, default)
            collected_values.append(value)
            per_item_breakdown[item_name] = (
                len(value) if isinstance(value, dict) else value
            )

        result_value = OPERATIONS[operation](collected_values)

    return {
        "status":      "ok",
        "description": model.get("description"),
        "operation":   operation,
        "value":       result_value,
        "breakdown":   per_item_breakdown
    }


# ---------------------------------------------------------------
# Output Formatting
# ---------------------------------------------------------------

def print_kpi_result(kpi_name: str,
                     model: dict,
                     result: dict,
                     router_name: str,
                     os_type: str,
                     input_dir: str) -> None:
    os_source    = model.get("source", {}).get(os_type, {})
    show_command = os_source.get("show_command", "N/A")
    input_file   = derive_filename(router_name, show_command, input_dir)

    print("\n" + "=" * 60)
    print(f"  KPI          : {kpi_name}")
    print("=" * 60)
    print(f"  Description  : {result.get('description')}")
    print(f"  Router       : {router_name}")
    print(f"  OS           : {os_type}")
    print(f"  Show Command : {show_command}")
    print(f"  Input Dir    : {input_dir}")
    print(f"  Input File   : {input_file}")
    print(f"  Status       : {result.get('status')}")
    print(f"  Operation    : {result.get('operation')}")
    if model.get("filter"):
        f = model.get("filter")
        print(f"  Filter       : {f.get('key')} == '{f.get('value')}'")
    print(f"\n  Breakdown:")
    for item, value in result.get("breakdown", {}).items():
        print(f"    {item:<25} : {value}")
    print(f"\n  Result Value : {result.get('value')}")
    print("=" * 60 + "\n")


# ---------------------------------------------------------------
# Main
# ---------------------------------------------------------------

def main():
    args        = parse_arguments()
    router_name = args.router
    os_type     = args.os
    models_file = args.models
    input_dir   = args.input_dir
    requested   = args.kpis
    parse_cache = {}

    kpi_models = load_kpi_models(models_file)

    if args.list_kpis:
        list_kpis(kpi_models)
        sys.exit(0)

    selected_models = select_kpis(kpi_models, requested)

    print(f"\n{'=' * 60}")
    print(f"  PyATS Offline KPI Calculator")
    print(f"  Router     : {router_name}")
    print(f"  OS         : {os_type}")
    print(f"  Models File: {models_file}")
    print(f"  Input Dir  : {input_dir}")
    print(f"  KPIs       : "
          f"{'all (' + str(len(selected_models)) + ')' if requested is None else str(requested)}")
    print(f"{'=' * 60}\n")

    if not os.path.isdir(input_dir):
        print(f"[ERROR] Input directory not found: '{input_dir}'")
        print(f"        Create it or use --input-dir "
              f"to specify a different path.")
        sys.exit(1)

    for kpi_name, model in selected_models.items():
        parsed_output = parse_output(
            model, router_name, os_type, input_dir, parse_cache
        )
        if parsed_output is None:
            print(f"[SKIP] KPI '{kpi_name}' -- "
                  f"OS '{os_type}' not supported.\n")
            continue

        result = calculate_kpi(model, parsed_output)
        print_kpi_result(
            kpi_name, model, result, router_name, os_type, input_dir
        )


if __name__ == "__main__":
    main()
