# tests/test_calculator.py
# Generated by CircuIT -- do not edit manually

import pytest
import json
import os
from kpi_calculator import (
    calculate_kpi,
    collect_leaf_items,
    resolve_path,
    select_kpis,
    build_json_output,
    write_json_output,
    VERBOSITY_SILENT
)


def test_resolve_path_single_key():
    data   = {"vrf": {"default": {"total_routes": 100}}}
    result = resolve_path(data, "vrf")
    assert "default" in result


def test_resolve_path_dot_notation():
    data   = {"mac_table": {"vlans": {"10": {"mac_addresses": {}}}}}
    result = resolve_path(data, "mac_table.vlans")
    assert "10" in result


def test_resolve_path_missing_key():
    data   = {"vrf": {}}
    result = resolve_path(data, "vrf.missing")
    assert result == {}


def test_collect_leaf_items_single_level():
    data = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5}
        }
    }
    items = collect_leaf_items(data, ["vrf"])
    assert len(items) == 2


def test_collect_leaf_items_two_levels():
    data = {
        "vrf": {
            "default": {
                "neighbor": {
                    "1.1.1.1": {"state": "Established"},
                    "2.2.2.2": {"state": "Established"}
                }
            }
        }
    }
    items = collect_leaf_items(data, ["vrf", "neighbor"])
    assert len(items) == 2


def test_calculate_kpi_sum():
    model  = {
        "description": "Total routes",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "sum",
        "default":     0
    }
    parsed = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5}
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 105


def test_calculate_kpi_count():
    model  = {
        "description": "Total VRFs",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "count",
        "default":     0
    }
    parsed = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5},
            "prod":    {"total_routes": 200}
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 3


def test_calculate_kpi_max():
    model  = {
        "description": "Max routes",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "max",
        "default":     0
    }
    parsed = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5},
            "prod":    {"total_routes": 200}
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 200


def test_calculate_kpi_with_filter():
    model  = {
        "description": "BFD Up",
        "iterate":     ["our_address", "neighbor_address"],
        "operation":   "count",
        "filter":      {"key": "state", "value": "Up"},
        "default":     0
    }
    parsed = {
        "our_address": {
            "10.0.0.1": {
                "neighbor_address": {
                    "10.0.0.2": {"state": "Up"},
                    "10.0.0.3": {"state": "Down"},
                    "10.0.0.4": {"state": "Up"}
                }
            }
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 2


def test_calculate_kpi_invalid_operation():
    model  = {
        "description": "Test",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "invalid",
        "default":     0
    }
    parsed = {"vrf": {"default": {"total_routes": 100}}}
    result = calculate_kpi(model, parsed)
    assert result["status"] == "error"


def test_calculate_kpi_empty_data():
    model  = {
        "description": "Test",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "sum",
        "default":     0
    }
    parsed = {"vrf": {}}
    result = calculate_kpi(model, parsed)
    assert result["status"] == "warning"
    assert result["value"]  == 0


SAMPLE_MODELS = {
    "total_routes": {
        "description": "Total routes",
        "source": {
            "nxos": {
                "show_command":  "show ip route summary",
                "parser_module": "genie.libs.parser.nxos.show_routing",
                "parser_class":  "ShowIpRouteSummary"
            }
        },
        "iterate":   "vrf",
        "value_key": "total_routes",
        "operation": "sum",
        "default":   0
    },
    "total_vrfs": {
        "description": "Total VRFs",
        "source": {
            "nxos": {
                "show_command":  "show ip route summary",
                "parser_module": "genie.libs.parser.nxos.show_routing",
                "parser_class":  "ShowIpRouteSummary"
            }
        },
        "iterate":   "vrf",
        "value_key": "total_routes",
        "operation": "count",
        "default":   0
    },
    "max_routes_in_vrf": {
        "description": "Max routes in VRF",
        "source": {
            "nxos": {
                "show_command":  "show ip route summary",
                "parser_module": "genie.libs.parser.nxos.show_routing",
                "parser_class":  "ShowIpRouteSummary"
            }
        },
        "iterate":   "vrf",
        "value_key": "total_routes",
        "operation": "max",
        "default":   0
    }
}


def test_select_kpis_none_returns_all():
    result = select_kpis(SAMPLE_MODELS, None)
    assert result == SAMPLE_MODELS


def test_select_kpis_single():
    result = select_kpis(SAMPLE_MODELS, ["total_routes"])
    assert list(result.keys()) == ["total_routes"]


def test_select_kpis_multiple():
    result = select_kpis(
        SAMPLE_MODELS, ["total_routes", "total_vrfs"]
    )
    assert set(result.keys()) == {"total_routes", "total_vrfs"}


def test_select_kpis_preserves_order():
    result = select_kpis(
        SAMPLE_MODELS,
        ["max_routes_in_vrf", "total_routes"]
    )
    assert list(result.keys()) == [
        "total_routes", "max_routes_in_vrf"
    ]


def test_select_kpis_unknown_exits():
    with pytest.raises(SystemExit):
        select_kpis(SAMPLE_MODELS, ["nonexistent_kpi"])


def test_select_kpis_partial_unknown_exits():
    with pytest.raises(SystemExit):
        select_kpis(
            SAMPLE_MODELS,
            ["total_routes", "nonexistent_kpi"]
        )


# ---------------------------------------------------------------
# JSON output tests
# ---------------------------------------------------------------

SAMPLE_RESULTS = {
    "total_routes": {
        "description": "Total routes",
        "value":       47,
        "status":      "ok",
        "operation":   "sum"
    },
    "total_vrfs": {
        "description": "Total VRFs",
        "value":       1,
        "status":      "ok",
        "operation":   "count"
    }
}


def test_build_json_output_structure():
    data = build_json_output("n7k", "nxos", SAMPLE_RESULTS)
    assert data["router"]    == "n7k"
    assert data["os"]        == "nxos"
    assert "timestamp"       in data
    assert "kpis"            in data
    assert "total_routes"    in data["kpis"]
    assert "total_vrfs"      in data["kpis"]


def test_build_json_output_kpi_fields():
    data = build_json_output("n7k", "nxos", SAMPLE_RESULTS)
    kpi  = data["kpis"]["total_routes"]
    assert kpi["value"]     == 47
    assert kpi["status"]    == "ok"
    assert kpi["operation"] == "sum"
    assert "description"    in kpi


def test_build_json_output_timestamp_format():
    data = build_json_output("n7k", "nxos", SAMPLE_RESULTS)
    from datetime import datetime
    datetime.fromisoformat(data["timestamp"])


def test_write_json_output_creates_file(tmp_path):
    filepath = str(tmp_path / "output.json")
    data     = build_json_output("n7k", "nxos", SAMPLE_RESULTS)
    write_json_output(data, filepath, VERBOSITY_SILENT)
    assert os.path.exists(filepath)


def test_write_json_output_valid_json(tmp_path):
    filepath = str(tmp_path / "output.json")
    data     = build_json_output("n7k", "nxos", SAMPLE_RESULTS)
    write_json_output(data, filepath, VERBOSITY_SILENT)
    with open(filepath) as f:
        loaded = json.load(f)
    assert loaded["router"] == "n7k"
    assert loaded["os"]     == "nxos"
    assert len(loaded["kpis"]) == 2


def test_write_json_output_correct_values(tmp_path):
    filepath = str(tmp_path / "output.json")
    data     = build_json_output("n7k", "nxos", SAMPLE_RESULTS)
    write_json_output(data, filepath, VERBOSITY_SILENT)
    with open(filepath) as f:
        loaded = json.load(f)
    assert loaded["kpis"]["total_routes"]["value"] == 47
    assert loaded["kpis"]["total_vrfs"]["value"]   == 1
