# tests/test_schema.py
# Generated by CircuIT — do not edit manually

import pytest
from schema import SchemaError
from kpi_calculator import (
    KPI_MODELS_SCHEMA,
    KPI_ENTRY_SCHEMA,
    OS_SOURCE_SCHEMA,
    FILTER_SCHEMA,
    validate_kpi_models
)


def test_valid_os_source_passes():
    OS_SOURCE_SCHEMA.validate({
        "show_command":  "show ip route summary",
        "parser_module": "genie.libs.parser.nxos.show_routing",
        "parser_class":  "ShowIpRouteSummary"
    })


def test_os_source_missing_field_fails():
    with pytest.raises(SchemaError):
        OS_SOURCE_SCHEMA.validate({
            "show_command":  "show ip route summary",
            "parser_module": "genie.libs.parser.nxos.show_routing"
        })


def test_os_source_empty_string_fails():
    with pytest.raises(SchemaError):
        OS_SOURCE_SCHEMA.validate({
            "show_command":  "",
            "parser_module": "genie.libs.parser.nxos.show_routing",
            "parser_class":  "ShowIpRouteSummary"
        })


def test_valid_filter_passes():
    FILTER_SCHEMA.validate({"key": "state", "value": "Up"})


def test_filter_empty_value_fails():
    with pytest.raises(SchemaError):
        FILTER_SCHEMA.validate({"key": "state", "value": ""})


def test_filter_missing_key_fails():
    with pytest.raises(SchemaError):
        FILTER_SCHEMA.validate({"value": "Up"})


def test_valid_entry_passes():
    KPI_ENTRY_SCHEMA.validate({
        "description": "Total routes",
        "source": {
            "nxos": {
                "show_command":  "show ip route summary",
                "parser_module": "genie.libs.parser.nxos.show_routing",
                "parser_class":  "ShowIpRouteSummary"
            }
        },
        "iterate":   "vrf",
        "value_key": "total_routes",
        "operation": "sum",
        "default":   0
    })


def test_invalid_os_key_fails():
    with pytest.raises(SchemaError):
        KPI_ENTRY_SCHEMA.validate({
            "description": "Total routes",
            "source": {
                "invalid_os": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "sum",
            "default":   0
        })


def test_invalid_operation_fails():
    with pytest.raises(SchemaError):
        KPI_ENTRY_SCHEMA.validate({
            "description": "Total routes",
            "source": {
                "nxos": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "invalid_op",
            "default":   0
        })


def test_negative_default_fails():
    with pytest.raises(SchemaError):
        KPI_ENTRY_SCHEMA.validate({
            "description": "Total routes",
            "source": {
                "nxos": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "sum",
            "default":   -1
        })


def test_list_iterate_passes():
    KPI_ENTRY_SCHEMA.validate({
        "description": "BGP neighbors",
        "source": {
            "nxos": {
                "show_command":  "show bgp summary",
                "parser_module": "genie.libs.parser.nxos.show_bgp",
                "parser_class":  "ShowBgpSummary"
            }
        },
        "iterate":   ["vrf", "neighbor"],
        "operation": "count",
        "default":   0
    })


def test_empty_list_iterate_fails():
    with pytest.raises(SchemaError):
        KPI_ENTRY_SCHEMA.validate({
            "description": "BGP neighbors",
            "source": {
                "nxos": {
                    "show_command":  "show bgp summary",
                    "parser_module": "genie.libs.parser.nxos.show_bgp",
                    "parser_class":  "ShowBgpSummary"
                }
            },
            "iterate":   [],
            "operation": "count",
            "default":   0
        })


def test_empty_source_fails():
    with pytest.raises(SchemaError):
        KPI_ENTRY_SCHEMA.validate({
            "description": "Total routes",
            "source":      {},
            "iterate":     "vrf",
            "operation":   "sum",
            "default":     0
        })


def test_optional_value_key_absent_passes():
    KPI_ENTRY_SCHEMA.validate({
        "description": "BGP neighbors",
        "source": {
            "nxos": {
                "show_command":  "show bgp summary",
                "parser_module": "genie.libs.parser.nxos.show_bgp",
                "parser_class":  "ShowBgpSummary"
            }
        },
        "iterate":   ["vrf", "neighbor"],
        "operation": "count",
        "default":   0
    })


def test_validate_kpi_models_all_valid():
    models = {
        "kpi_one": {
            "description": "KPI one",
            "source": {
                "nxos": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "sum",
            "default":   0
        }
    }
    assert validate_kpi_models(models) is True


def test_validate_kpi_models_reports_all_failures():
    models = {
        "kpi_good": {
            "description": "Good KPI",
            "source": {
                "nxos": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "sum",
            "default":   0
        },
        "kpi_bad": {
            "description": "Bad KPI",
            "source": {
                "nxos": {
                    "show_command":  "show ip route summary",
                    "parser_module": "genie.libs.parser.nxos.show_routing",
                    "parser_class":  "ShowIpRouteSummary"
                }
            },
            "iterate":   "vrf",
            "operation": "invalid_op",
            "default":   0
        }
    }
    assert validate_kpi_models(models) is False
