# tests/test_calculator.py
# Generated by CircuIT — do not edit manually

import pytest
from kpi_calculator import calculate_kpi, collect_leaf_items, resolve_path


def test_resolve_path_single_key():
    data   = {"vrf": {"default": {"total_routes": 100}}}
    result = resolve_path(data, "vrf")
    assert "default" in result


def test_resolve_path_dot_notation():
    data   = {"mac_table": {"vlans": {"10": {"mac_addresses": {}}}}}
    result = resolve_path(data, "mac_table.vlans")
    assert "10" in result


def test_resolve_path_missing_key():
    data   = {"vrf": {}}
    result = resolve_path(data, "vrf.missing")
    assert result == {}


def test_collect_leaf_items_single_level():
    data = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5}
        }
    }
    items = collect_leaf_items(data, ["vrf"])
    assert len(items) == 2


def test_collect_leaf_items_two_levels():
    data = {
        "vrf": {
            "default": {
                "neighbor": {
                    "1.1.1.1": {"state": "Established"},
                    "2.2.2.2": {"state": "Established"}
                }
            }
        }
    }
    items = collect_leaf_items(data, ["vrf", "neighbor"])
    assert len(items) == 2


def test_calculate_kpi_sum():
    model  = {
        "description": "Total routes",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "sum",
        "default":     0
    }
    parsed = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5}
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 105


def test_calculate_kpi_count():
    model  = {
        "description": "Total VRFs",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "count",
        "default":     0
    }
    parsed = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5},
            "prod":    {"total_routes": 200}
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 3


def test_calculate_kpi_max():
    model  = {
        "description": "Max routes",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "max",
        "default":     0
    }
    parsed = {
        "vrf": {
            "default": {"total_routes": 100},
            "mgmt":    {"total_routes": 5},
            "prod":    {"total_routes": 200}
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 200


def test_calculate_kpi_with_filter():
    model  = {
        "description": "BFD Up",
        "iterate":     ["our_address", "neighbor_address"],
        "operation":   "count",
        "filter":      {"key": "state", "value": "Up"},
        "default":     0
    }
    parsed = {
        "our_address": {
            "10.0.0.1": {
                "neighbor_address": {
                    "10.0.0.2": {"state": "Up"},
                    "10.0.0.3": {"state": "Down"},
                    "10.0.0.4": {"state": "Up"}
                }
            }
        }
    }
    result = calculate_kpi(model, parsed)
    assert result["status"] == "ok"
    assert result["value"]  == 2


def test_calculate_kpi_invalid_operation():
    model  = {
        "description": "Test",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "invalid",
        "default":     0
    }
    parsed = {"vrf": {"default": {"total_routes": 100}}}
    result = calculate_kpi(model, parsed)
    assert result["status"] == "error"


def test_calculate_kpi_empty_data():
    model  = {
        "description": "Test",
        "iterate":     "vrf",
        "value_key":   "total_routes",
        "operation":   "sum",
        "default":     0
    }
    parsed = {"vrf": {}}
    result = calculate_kpi(model, parsed)
    assert result["status"] == "warning"
    assert result["value"]  == 0
