# tests/test_parser.py
# Generated by CircuIT — do not edit manually

import pytest
from unittest.mock import MagicMock, patch
from kpi_calculator import (
    derive_filename,
    resolve_parser_class,
    _try_parse,
    PARSE_PARAMS
)


def test_derive_filename_basic():
    result = derive_filename(
        "LaMSC1DC01", "show ip route summary"
    )
    assert result == "input_files/LaMSC1DC01__show_ip_route_summary.txt"


def test_derive_filename_custom_input_dir():
    result = derive_filename(
        "LaMSC1DC01", "show ip route summary",
        input_dir="/data/captures"
    )
    assert result ==         "/data/captures/LaMSC1DC01__show_ip_route_summary.txt"


def test_derive_filename_with_hyphen():
    result = derive_filename(
        "core-sw-01", "show mac address-table"
    )
    assert result ==         "input_files/core-sw-01__show_mac_address-table.txt"


def test_derive_filename_iosxr_command():
    result = derive_filename(
        "pe-router-01", "show route summary"
    )
    assert result == "input_files/pe-router-01__show_route_summary.txt"


def test_derive_filename_custom_extension():
    result = derive_filename(
        "LaMSC1DC01", "show ip route summary",
        extension="log"
    )
    assert result == "input_files/LaMSC1DC01__show_ip_route_summary.log"


def test_resolve_valid_parser_class():
    cls = resolve_parser_class(
        "genie.libs.parser.nxos.show_routing",
        "ShowIpRouteSummary"
    )
    assert cls is not None


def test_resolve_invalid_module():
    with pytest.raises(SystemExit):
        resolve_parser_class(
            "genie.libs.parser.nxos.nonexistent_module",
            "ShowIpRouteSummary"
        )


def test_resolve_invalid_class():
    with pytest.raises(SystemExit):
        resolve_parser_class(
            "genie.libs.parser.nxos.show_routing",
            "NonExistentClass"
        )


def test_parse_params_order():
    """output= should be tried before text= for NX-OS compatibility."""
    assert PARSE_PARAMS[0] == "output"
    assert PARSE_PARAMS[1] == "text"


def test_try_parse_uses_output_param():
    """
    Verify _try_parse tries output= first and returns
    result on success.
    """
    mock_device = MagicMock()
    mock_result = {"vrf": {"default": {"total_routes": 47}}}

    mock_parser_instance = MagicMock()
    mock_parser_instance.parse.return_value = mock_result

    mock_parser_class = MagicMock(return_value=mock_parser_instance)

    result = _try_parse(
        mock_parser_class,
        mock_device,
        "raw output text",
        "show ip route summary"
    )

    assert result == mock_result
    mock_parser_instance.parse.assert_called_once_with(
        output="raw output text"
    )


def test_try_parse_falls_back_to_text_param():
    """
    Verify _try_parse falls back to text= when output= raises TypeError.
    """
    mock_device = MagicMock()
    mock_result = {"vrf": {"default": {"total_routes": 47}}}

    mock_parser_instance = MagicMock()
    mock_parser_instance.parse.side_effect = [
        TypeError("unexpected keyword argument 'output'"),
        mock_result
    ]

    mock_parser_class = MagicMock(return_value=mock_parser_instance)

    result = _try_parse(
        mock_parser_class,
        mock_device,
        "raw output text",
        "show ip route summary"
    )

    assert result == mock_result
    assert mock_parser_instance.parse.call_count == 2
