# tests/test_parser.py
# Generated by CircuIT — do not edit manually

import pytest
from kpi_calculator import derive_filename, resolve_parser_class


def test_derive_filename_basic():
    result = derive_filename("core-sw-01", "show ip route summary")
    assert result == "core-sw-01__show_ip_route_summary.txt"


def test_derive_filename_with_hyphen():
    result = derive_filename("core-sw-01", "show mac address-table")
    assert result == "core-sw-01__show_mac_address-table.txt"


def test_derive_filename_iosxr_command():
    result = derive_filename("pe-router-01", "show route summary")
    assert result == "pe-router-01__show_route_summary.txt"


def test_derive_filename_custom_extension():
    result = derive_filename(
        "core-sw-01", "show ip route summary", extension="log"
    )
    assert result == "core-sw-01__show_ip_route_summary.log"


def test_resolve_valid_parser_class():
    cls = resolve_parser_class(
        "genie.libs.parser.nxos.show_routing",
        "ShowIpRouteSummary"
    )
    assert cls is not None


def test_resolve_invalid_module():
    with pytest.raises(SystemExit):
        resolve_parser_class(
            "genie.libs.parser.nxos.nonexistent_module",
            "ShowIpRouteSummary"
        )


def test_resolve_invalid_class():
    with pytest.raises(SystemExit):
        resolve_parser_class(
            "genie.libs.parser.nxos.show_routing",
            "NonExistentClass"
        )
